FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/worker-service ./cmd/worker-service

FROM gcr.io/distroless/base-debian12
COPY --from=builder /bin/worker-service /bin/worker-service
EXPOSE 8083
ENTRYPOINT ["/bin/worker-service"]
