import { StyleSheet } from "react-native";
import { theme } from "../../../theme/themes";
import { NODE_SIZE, NODE_DEPTH } from "./constants";

export const s = StyleSheet.create({
  scrollContent: {
    backgroundColor: theme.colors.background,
    paddingBottom: 40,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 14,
    alignSelf: "flex-start",
  },
  backBtnText: {
    color: theme.colors.primary,
    fontSize: 15,
    fontFamily: "Nunito_700Bold",
  },
  phaseHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
  },
  phaseRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  phaseTitle: {
    color: theme.colors.text,
    fontSize: 20,
    fontFamily: "Nunito_900Black",
    letterSpacing: 0.3,
  },
  phaseSubtitle: {
    color: theme.colors.textMuted,
    fontSize: 13,
    marginTop: 4,
  },
  summaryCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  summaryItem: { alignItems: "center" },
  summaryValue: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: "Nunito_900Black",
  },
  summaryLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  summaryDivider: {
    width: 1,
    height: 28,
    backgroundColor: theme.colors.outline,
  },
  summaryBar: {
    height: 6,
    backgroundColor: theme.colors.surfaceHigh,
    borderRadius: 3,
    marginTop: 14,
    overflow: "hidden",
  },
  summaryBarFill: {
    height: "100%",
    backgroundColor: theme.colors.primary,
    borderRadius: 3,
  },
  nodeRow: {
    width: "100%",
    alignItems: "center",
    paddingVertical: 20,
  },
  nodeWrapper: {
    alignItems: "center",
    width: NODE_SIZE + 100,
  },
  touchableArea: {
    width: NODE_SIZE,
    height: NODE_SIZE + NODE_DEPTH,
    justifyContent: "center",
    alignItems: "center",
  },
  nodeBase: {
    position: "absolute",
    width: NODE_SIZE + 20,
    height: NODE_SIZE + 20,
    borderRadius: (NODE_SIZE + 20) / 2,
  },
  nodeBottom: {
    position: "absolute",
    width: NODE_SIZE,
    height: NODE_SIZE,
    borderRadius: NODE_SIZE / 2,
    top: NODE_DEPTH,
  },
  progressArcContainer: {
    position: "absolute",
    width: NODE_SIZE + 12,
    height: NODE_SIZE + 12,
    borderRadius: (NODE_SIZE + 12) / 2,
    overflow: "hidden",
  },
  progressArc: {
    position: "absolute",
    width: NODE_SIZE + 12,
    height: NODE_SIZE + 12,
    borderRadius: (NODE_SIZE + 12) / 2,
    borderWidth: 5,
    borderColor: "transparent",
    borderTopColor: theme.colors.secondary,
    borderRightColor: theme.colors.secondary,
    transform: [{ rotate: "-45deg" }],
  },
  nodeTop: {
    width: NODE_SIZE,
    height: NODE_SIZE,
    borderRadius: NODE_SIZE / 2,
    borderWidth: 3,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  nodeLabel: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    marginTop: 8,
    textAlign: "center",
    maxWidth: NODE_SIZE + 60,
  },
  nodeLabelLocked: {
    color: theme.colors.textMuted,
    opacity: 0.5,
  },
  progressPill: {
    backgroundColor: theme.colors.primary18,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 999,
    marginTop: 5,
  },
  progressText: {
    color: theme.colors.primary,
    fontSize: 11,
    fontFamily: "Nunito_800ExtraBold",
  },
  treasureBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: theme.colors.secondary20,
    padding: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.secondary35,
  },
});
