package progress

// SeedLevels returns all seeded learning journeys.
func SeedLevels() []Level {
	return withCourseDefaults(seedQaidaLevels(), CourseQaida, 0)
}

func withCourseDefaults(levels []Level, courseType CourseType, idOffset int) []Level {
	for i := range levels {
		levels[i].CourseType = courseType
		if levels[i].CourseLevel == 0 {
			levels[i].CourseLevel = i + 1
		}
		if levels[i].ID == 0 {
			levels[i].ID = idOffset + levels[i].CourseLevel
		}
	}
	return levels
}

// Noorani Qaida journey. Interactive tasks use pure Arabic (Arabic script,
// no romanization); English appears only as instructions/translations on
// reading cards. Component names map to React components in the app's
// LESSON_COMPONENT_MAP / mini-game router.
func seedQaidaLevels() []Level {
	return []Level{
		// ───────── LEVELS 1-5: The Arabic Alphabet ─────────
		{
			ID:           1,
			Title:        "The First Letters",
			Theme:        "Arabic Alphabet Discovery",
			Goal:         "Meet your first five Arabic letters (ا to ج)",
			Difficulty:   LevelEasy,
			XPReward:     50,
			UnlockReward: "badge:first_step",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet the Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", SkillTags: []string{"ا", "ب", "ت", "ث", "ج"}, Data: map[string]any{"letters": []map[string]any{{"letter": "ا", "name": "أَلِف"}, {"letter": "ب", "name": "بَاء"}, {"letter": "ت", "name": "تَاء"}, {"letter": "ث", "name": "ثَاء"}, {"letter": "ج", "name": "جِيم"}}}},
				{Type: LessonQaida, Title: "Match the Names", Description: "Match each letter with its name", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its Arabic name", "pairs": []map[string]any{{"left": "ا", "right": "أَلِف"}, {"left": "ب", "right": "بَاء"}, {"left": "ت", "right": "تَاء"}, {"left": "ج", "right": "جِيم"}}}},
				{Type: LessonPronunciation, Title: "Listen & Choose", Description: "Listen, then tap the letter you heard", ScreenType: ScreenAction, Component: "ListenChooseComponent", Data: map[string]any{"audio": "ج", "options": []string{"ج", "ت", "ب"}, "correct": 0}},
				{Type: LessonQaida, Title: "Letter Hunt", Description: "Find every تَاء in the grid", ScreenType: ScreenAction, Component: "LetterHuntComponent", SkillTags: []string{"ت"}, Data: map[string]any{"instruction": "Tap every ت — watch out for lookalikes!", "target": "ت", "grid": []string{"ب", "ت", "ث", "ت", "ج", "ب", "ت", "ث", "ا", "ت", "ب", "ج"}}},
				{Type: LessonQuiz, Title: "Spot the Letter", Description: "Choose the correct letter", ScreenType: ScreenQuiz, Component: "MCQComponent", SkillTags: []string{"ث"}, Data: map[string]any{"question": "Tap the letter that has three dots above it", "options": []string{"ب", "ت", "ث", "ج"}, "correct": 2}},
				{Type: LessonDua, Title: "Before Eating", Description: "A short dua to say before eating", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ", "meaning": "In the name of Allah", "context": "Say this before you start eating"}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match each letter to its name", SkillTags: []string{"ا", "ب", "ت", "ث", "ج"}, Data: map[string]any{"pairs": []map[string]any{{"left": "ا", "right": "أَلِف"}, {"left": "ب", "right": "بَاء"}, {"left": "ت", "right": "تَاء"}, {"left": "ث", "right": "ثَاء"}, {"left": "ج", "right": "جِيم"}}}},
		},
		{
			ID:           2,
			Title:        "More Letters!",
			Theme:        "Arabic Alphabet Expansion",
			Goal:         "Learn letters ح to ز",
			Difficulty:   LevelEasy,
			XPReward:     60,
			UnlockReward: "badge:letter_explorer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet the Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ح", "name": "حَاء"}, {"letter": "خ", "name": "خَاء"}, {"letter": "د", "name": "دَال"}, {"letter": "ذ", "name": "ذَال"}, {"letter": "ر", "name": "رَاء"}, {"letter": "ز", "name": "زَاي"}}}},
				{Type: LessonPronunciation, Title: "Listen & Choose", Description: "Listen, then tap the letter you heard", ScreenType: ScreenAction, Component: "ListenChooseComponent", Data: map[string]any{"audio": "خ", "options": []string{"ح", "خ", "ج"}, "correct": 1}},
				{Type: LessonQuiz, Title: "True or False?", Description: "Check the dots carefully", ScreenType: ScreenQuiz, Component: "TrueFalseComponent", Data: map[string]any{"rounds": []map[string]any{{"prompt": "This letter has one dot above it", "arabic": "خ", "answer": true}, {"prompt": "This letter has a dot below it", "arabic": "ح", "answer": false}, {"prompt": "This letter has one dot above it", "arabic": "ذ", "answer": true}, {"prompt": "This letter has a dot above it", "arabic": "د", "answer": false}}}},
				{Type: LessonQaida, Title: "Match the Names", Description: "Match each letter with its name", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its Arabic name", "pairs": []map[string]any{{"left": "ح", "right": "حَاء"}, {"left": "خ", "right": "خَاء"}, {"left": "د", "right": "دَال"}, {"left": "ذ", "right": "ذَال"}}}},
				{Type: LessonQuiz, Title: "Spot the Letter", Description: "Choose the correct letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which letter has a single dot above it?", "options": []string{"د", "ذ", "ر", "ز"}, "correct": 1}},
				{Type: LessonHadith, Title: "Intentions Matter", Description: "A hadith about intentions", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Actions are judged by intentions, and every person will get what they intended.", "reference": "Bukhari & Muslim"}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "Flip the cards to match each letter with its name", Data: map[string]any{"pairs": []map[string]any{{"left": "ح", "right": "حَاء"}, {"left": "خ", "right": "خَاء"}, {"left": "د", "right": "دَال"}, {"left": "ذ", "right": "ذَال"}, {"left": "ر", "right": "رَاء"}, {"left": "ز", "right": "زَاي"}}}},
		},
		{
			ID:           3,
			Title:        "Halfway There!",
			Theme:        "Arabic Alphabet Continues",
			Goal:         "Learn letters س to ض",
			Difficulty:   LevelEasy,
			XPReward:     70,
			UnlockReward: "title:alphabet_adventurer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet the Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "س", "name": "سِين"}, {"letter": "ش", "name": "شِين"}, {"letter": "ص", "name": "صَاد"}, {"letter": "ض", "name": "ضَاد"}}}},
				{Type: LessonQaida, Title: "Match the Names", Description: "Match each letter with its name", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its Arabic name", "pairs": []map[string]any{{"left": "س", "right": "سِين"}, {"left": "ش", "right": "شِين"}, {"left": "ص", "right": "صَاد"}, {"left": "ض", "right": "ضَاد"}}}},
				{Type: LessonQaida, Title: "Sort the Letters", Description: "Dots or no dots?", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each letter: does it have dots?", "buckets": []string{"بِنُقَط", "بِدُونِ نُقَط"}, "items": []map[string]any{{"text": "ش", "bucket": 0}, {"text": "ض", "bucket": 0}, {"text": "س", "bucket": 1}, {"text": "ص", "bucket": 1}}}},
				{Type: LessonPronunciation, Title: "Listen & Choose", Description: "Listen, then tap the letter you heard", ScreenType: ScreenAction, Component: "ListenChooseComponent", Data: map[string]any{"audio": "ش", "options": []string{"س", "ش", "ص"}, "correct": 1}},
				{Type: LessonManners, Title: "Say Salam!", Description: "The beautiful Islamic greeting", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Say السَّلَامُ عَلَيْكُم when you meet someone", "It means: Peace be upon you", "The reply is وَعَلَيْكُمُ السَّلَام", "Spreading salam spreads love and peace"}}},
				{Type: LessonQuiz, Title: "Spot the Letter", Description: "Choose the correct letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Tap the letter شِين", "options": []string{"س", "ش", "ص", "ض"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match each letter to its name", Data: map[string]any{"pairs": []map[string]any{{"left": "س", "right": "سِين"}, {"left": "ش", "right": "شِين"}, {"left": "ص", "right": "صَاد"}, {"left": "ض", "right": "ضَاد"}}}},
		},
		{
			ID:           4,
			Title:        "Almost All Letters!",
			Theme:        "Arabic Alphabet Mastery",
			Goal:         "Learn letters ط to غ",
			Difficulty:   LevelEasy,
			XPReward:     80,
			UnlockReward: "badge:dua_learner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet the Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ط", "name": "طَاء"}, {"letter": "ظ", "name": "ظَاء"}, {"letter": "ع", "name": "عَين"}, {"letter": "غ", "name": "غَين"}}}},
				{Type: LessonQaida, Title: "Match the Names", Description: "Match each letter with its name", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its Arabic name", "pairs": []map[string]any{{"left": "ط", "right": "طَاء"}, {"left": "ظ", "right": "ظَاء"}, {"left": "ع", "right": "عَين"}, {"left": "غ", "right": "غَين"}}}},
				{Type: LessonQaida, Title: "Letter Hunt", Description: "Find every غَين", ScreenType: ScreenAction, Component: "LetterHuntComponent", Data: map[string]any{"instruction": "Tap every غ — do not confuse it with ع!", "target": "غ", "grid": []string{"ع", "غ", "ط", "غ", "ع", "ظ", "غ", "ع"}}},
				{Type: LessonDua, Title: "Before Sleep", Description: "A dua to say before sleeping", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", "meaning": "In Your name, O Allah, I die and I live", "context": "Say this before going to sleep"}},
				{Type: LessonQuiz, Title: "Spot the Letter", Description: "Choose the correct letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Tap the letter غَين", "options": []string{"ط", "ظ", "ع", "غ"}, "correct": 3}},
				{Type: LessonPronunciation, Title: "Listen Challenge", Description: "Listen and choose each letter", ScreenType: ScreenAction, Component: "ListenChooseComponent", Data: map[string]any{"audio": "ع", "options": []string{"ع", "غ", "ح"}, "correct": 0}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen to each letter and choose it", Data: map[string]any{"questions": []map[string]any{{"audio": "ط", "options": []string{"ط", "ت", "ظ"}, "correct": 0}, {"audio": "غ", "options": []string{"ع", "غ", "ح"}, "correct": 1}}}},
		},
		{
			ID:           5,
			Title:        "Alphabet Complete!",
			Theme:        "Arabic Alphabet Celebration",
			Goal:         "Learn the final letters (ف to ي) and finish the alphabet",
			Difficulty:   LevelEasy,
			XPReward:     100,
			UnlockReward: "badge:alphabet_master",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet the Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ف", "name": "فَاء"}, {"letter": "ق", "name": "قَاف"}, {"letter": "ك", "name": "كَاف"}, {"letter": "ل", "name": "لَام"}, {"letter": "م", "name": "مِيم"}}}},
				{Type: LessonQaida, Title: "Final Letters", Description: "Tap each letter to hear it", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ن", "name": "نُون"}, {"letter": "ه", "name": "هَاء"}, {"letter": "و", "name": "وَاو"}, {"letter": "ي", "name": "يَاء"}}}},
				{Type: LessonQaida, Title: "Match the Names", Description: "Match each letter with its name", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its Arabic name", "pairs": []map[string]any{{"left": "ف", "right": "فَاء"}, {"left": "ق", "right": "قَاف"}, {"left": "ك", "right": "كَاف"}, {"left": "ن", "right": "نُون"}}}},
				{Type: LessonRevision, Title: "Lightning Round", Description: "Beat the clock!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 7, "questions": []map[string]any{{"question": "Tap the letter نُون", "options": []string{"ن", "ب", "ت"}, "correct": 0}, {"question": "Tap the letter وَاو", "options": []string{"ز", "و", "ر"}, "correct": 1}, {"question": "Tap the letter مِيم", "options": []string{"ه", "ن", "م"}, "correct": 2}, {"question": "Tap the letter يَاء", "options": []string{"ي", "ب", "ن"}, "correct": 0}}}},
				{Type: LessonHadith, Title: "Cleanliness", Description: "Cleanliness in Islam", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Cleanliness is half of faith.", "reference": "Sahih Muslim"}},
				{Type: LessonRevision, Title: "Alphabet Check", Description: "How many letters?", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How many letters are in the Arabic alphabet?", "options": []string{"٢٦", "٢٧", "٢٨", "٢٩"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Treasure! Match all the final letters with their names", Data: map[string]any{"pairs": []map[string]any{{"left": "ف", "right": "فَاء"}, {"left": "ق", "right": "قَاف"}, {"left": "ك", "right": "كَاف"}, {"left": "ل", "right": "لَام"}, {"left": "م", "right": "مِيم"}, {"left": "ن", "right": "نُون"}}}},
		},

		// ───────── LEVELS 6-10: Harakat & First Words ─────────
		{
			ID:           6,
			Title:        "Zabar Power!",
			Theme:        "Harakat – Fathah",
			Goal:         "Learn the Fathah and read letters with an 'a' sound",
			Difficulty:   LevelMedium,
			XPReward:     100,
			UnlockReward: "badge:harakat_beginner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Fathah?", Description: "A small stroke above the letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بَ", "name": "الفَتْحَة", "note": "الفَتْحَة عَلامَة فَوْقَ الحَرْف"}},
				{Type: LessonPronunciation, Title: "Practice Fathah", Description: "Tap each to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "بَ"}, {"arabic": "تَ"}, {"arabic": "ثَ"}, {"arabic": "جَ"}, {"arabic": "دَ"}}}},
				{Type: LessonQuiz, Title: "Fathah or Not?", Description: "True or false — look closely", ScreenType: ScreenQuiz, Component: "TrueFalseComponent", Data: map[string]any{"rounds": []map[string]any{{"prompt": "This letter has a Fathah", "arabic": "بَ", "answer": true}, {"prompt": "This letter has a Fathah", "arabic": "بِ", "answer": false}, {"prompt": "This letter has a Fathah", "arabic": "تَ", "answer": true}, {"prompt": "This letter has a Fathah", "arabic": "مُ", "answer": false}}}},
				{Type: LessonPronunciation, Title: "Listen & Choose", Description: "Which letter has the Fathah?", ScreenType: ScreenAction, Component: "ListenChooseComponent", Data: map[string]any{"audio": "سَ", "options": []string{"سَ", "شَ", "صَ"}, "correct": 0}},
				{Type: LessonQuiz, Title: "Where is the Fathah?", Description: "Choose the correct position", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Where is the Fathah placed?", "options": []string{"فَوْقَ الحَرْف", "تَحْتَ الحَرْف", "أَمَامَ الحَرْف"}, "correct": 0}},
				{Type: LessonDua, Title: "Entering Home", Description: "A dua for entering your home", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ وَلَجْنَا", "meaning": "In the name of Allah we enter", "context": "Say this when entering your home"}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Choose the letter with a Fathah", Data: map[string]any{"questions": []map[string]any{{"question": "Which letter has a Fathah (  َ )?", "options": []string{"مَ", "م", "مِ"}, "correct": 0}, {"question": "Which letter has a Fathah (  َ )?", "options": []string{"كُ", "كِ", "كَ"}, "correct": 2}}}},
		},
		{
			ID:           7,
			Title:        "Zer & Pesh",
			Theme:        "Harakat – Kasrah & Dammah",
			Goal:         "Complete the three harakat: Kasrah and Dammah",
			Difficulty:   LevelMedium,
			XPReward:     110,
			UnlockReward: "badge:harakat_explorer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Kasrah & Dammah", Description: "One sits below, one sits above", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "بِ", "name": "الكَسْرَة"}, {"letter": "بُ", "name": "الضَّمَّة"}}}},
				{Type: LessonPronunciation, Title: "All Three Harakat", Description: "Tap each to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "بَ بِ بُ"}, {"arabic": "تَ تِ تُ"}, {"arabic": "سَ سِ سُ"}}}},
				{Type: LessonQaida, Title: "Sort the Harakat", Description: "Kasrah or Dammah?", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each letter by its harakat", "buckets": []string{"كَسْرَة", "ضَمَّة"}, "items": []map[string]any{{"text": "بِ", "bucket": 0}, {"text": "سُ", "bucket": 1}, {"text": "تِ", "bucket": 0}, {"text": "مُ", "bucket": 1}}}},
				{Type: LessonQaida, Title: "Match the Harakat", Description: "Match each letter to its harakat", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each to its harakat", "pairs": []map[string]any{{"left": "بَ", "right": "فَتْحَة"}, {"left": "بِ", "right": "كَسْرَة"}, {"left": "بُ", "right": "ضَمَّة"}}}},
				{Type: LessonHadith, Title: "Kindness", Description: "Allah loves kindness", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Allah is kind and loves kindness in all matters.", "reference": "Bukhari & Muslim"}},
				{Type: LessonQuiz, Title: "Find the Dammah", Description: "Choose the correct letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which letter has a Dammah (  ُ )?", "options": []string{"بَ", "بِ", "بُ"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Build the harakat in order: Fathah, Kasrah, Dammah", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"بَ", "بِ", "بُ"}, "word": "بَ بِ بُ", "meaning": "Fathah · Kasrah · Dammah"}, {"parts": []string{"تَ", "تِ", "تُ"}, "word": "تَ تِ تُ", "meaning": "Fathah · Kasrah · Dammah"}}}},
		},
		{
			ID:           8,
			Title:        "Two-Letter Words",
			Theme:        "Building Blocks",
			Goal:         "Learn Sukoon and read your first 2-letter words",
			Difficulty:   LevelMedium,
			XPReward:     120,
			UnlockReward: "title:word_builder",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Sukoon?", Description: "It makes a letter silent", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بْ", "name": "السُّكُون", "note": "السُّكُون يُسَكِّن الحَرْف"}},
				{Type: LessonPronunciation, Title: "First Words!", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "أَبْ"}, {"arabic": "أُمْ"}, {"arabic": "مِنْ"}}}},
				{Type: LessonQaida, Title: "Build the Word", Description: "One tile does not belong!", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the word — one tile is a decoy", "parts": []string{"أُ", "مْ"}, "distractors": []string{"بْ"}, "meaning": "Mother"}},
				{Type: LessonQaida, Title: "Complete the Word", Description: "Pick the missing letter", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the word", "sentence": []map[string]any{{"text": "أُ"}, {"blank": true, "answer": "مْ"}}, "bank": []string{"مْ", "بْ", "نْ"}, "meaning": "Mother"}},
				{Type: LessonQuiz, Title: "Word Meaning", Description: "Choose the right word", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which word means 'from'?", "options": []string{"مِنْ", "مَنْ", "هَلْ"}, "correct": 0}},
				{Type: LessonManners, Title: "Helping Others", Description: "The reward of helping", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Helping others is a form of صَدَقَة", "Even a smile is charity in Islam", "Help your family with daily chores", "Be the first to offer help"}}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Build each 2-letter word from its parts", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"مِ", "نْ"}, "word": "مِنْ", "meaning": "From"}, {"parts": []string{"قُ", "لْ"}, "word": "قُلْ", "meaning": "Say!"}, {"parts": []string{"هَ", "لْ"}, "word": "هَلْ", "meaning": "Question word"}}}},
		},
		{
			ID:           9,
			Title:        "Three-Letter Words",
			Theme:        "Growing Confidence",
			Goal:         "Read your first 3-letter Arabic words",
			Difficulty:   LevelMedium,
			XPReward:     130,
			UnlockReward: "badge:reader_rising",
			Lessons: []Lesson{
				{Type: LessonPronunciation, Title: "3-Letter Words", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "كَتَبَ"}, {"arabic": "جَلَسَ"}, {"arabic": "فَتَحَ"}}}},
				{Type: LessonQaida, Title: "Build the Word", Description: "Arrange the parts in order", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the word — one tile is a decoy", "parts": []string{"كَ", "تَ", "بَ"}, "distractors": []string{"كِ"}, "meaning": "He wrote"}},
				{Type: LessonQaida, Title: "Complete the Word", Description: "Pick the missing part", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the word", "sentence": []map[string]any{{"text": "جَ"}, {"blank": true, "answer": "لَ"}, {"text": "سَ"}}, "bank": []string{"لَ", "لِ", "لُ"}, "meaning": "He sat"}},
				{Type: LessonQuiz, Title: "Lightning Meanings", Description: "Beat the clock!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 8, "questions": []map[string]any{{"question": "Which word means 'He sat'?", "options": []string{"كَتَبَ", "جَلَسَ", "فَتَحَ"}, "correct": 1}, {"question": "Which word means 'He wrote'?", "options": []string{"كَتَبَ", "جَلَسَ", "فَتَحَ"}, "correct": 0}, {"question": "Which word means 'He opened'?", "options": []string{"كَتَبَ", "جَلَسَ", "فَتَحَ"}, "correct": 2}}}},
				{Type: LessonHadith, Title: "Truthfulness", Description: "Truthfulness leads to good", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Truthfulness leads to righteousness and righteousness leads to Paradise.", "reference": "Bukhari & Muslim"}},
				{Type: LessonDua, Title: "Leaving Home", Description: "A dua for leaving home", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ", "meaning": "In the name of Allah, I place my trust in Allah", "context": "Say this when leaving your home"}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Build each 3-letter word", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"نَ", "صَ", "رَ"}, "word": "نَصَرَ", "meaning": "He helped"}, {"parts": []string{"ذَ", "هَ", "بَ"}, "word": "ذَهَبَ", "meaning": "He went"}}}},
		},
		{
			ID:           10,
			Title:        "Tanween Time!",
			Theme:        "Double Harakat",
			Goal:         "Learn the three Tanween endings",
			Difficulty:   LevelMedium,
			XPReward:     150,
			UnlockReward: "badge:tanween_master",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "The Three Tanween", Description: "Double harakat at the end of a word", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ـً", "name": "تَنْوِين الفَتْح"}, {"letter": "ـٍ", "name": "تَنْوِين الكَسْر"}, {"letter": "ـٌ", "name": "تَنْوِين الضَّم"}}}},
				{Type: LessonPronunciation, Title: "Read Tanween", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "كِتَابًا"}, {"arabic": "كِتَابٍ"}, {"arabic": "كِتَابٌ"}}}},
				{Type: LessonQaida, Title: "Sort the Tanween", Description: "Fath or Damm?", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each word by its tanween", "hint": "Check the sign on the last letter, then drop the word in its matching bucket.", "bucketHints": []string{"ـً", "ـٌ"}, "buckets": []string{"تَنْوِين فَتْح", "تَنْوِين ضَم"}, "items": []map[string]any{{"text": "كِتَابًا", "bucket": 0}, {"text": "كِتَابٌ", "bucket": 1}, {"text": "نُورًا", "bucket": 0}, {"text": "عِلْمٌ", "bucket": 1}}}},
				{Type: LessonQaida, Title: "Match the Tanween", Description: "Match each word to its tanween", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each word to its tanween", "pairs": []map[string]any{{"left": "كِتَابًا", "right": "تَنْوِين الفَتْح"}, {"left": "كِتَابٍ", "right": "تَنْوِين الكَسْر"}, {"left": "كِتَابٌ", "right": "تَنْوِين الضَّم"}}}},
				{Type: LessonQuiz, Title: "Find the Tanween", Description: "Choose the correct ending", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which word has Tanween Fathah (ـً)?", "hint": "Tanween Fathah is two slanted strokes above the last letter:", "hintArabic": "ـً", "options": []string{"نُورًا", "نُورٍ", "نُورٌ"}, "correct": 0}},
				{Type: LessonManners, Title: "Respect Elders", Description: "Honour those older than you", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Stand and welcome elders with respect", "Speak softly and politely to them", "Listen without interrupting", "The Prophet ﷺ taught us to honour our elders"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "🎁 Treasure! Identify each Tanween ending", Data: map[string]any{"questions": []map[string]any{{"question": "Which word has Tanween Dammah (ـٌ)?", "hint": "Tanween Dammah looks like a small doubled و above:", "hintArabic": "ـٌ", "options": []string{"عِلْمًا", "عِلْمٍ", "عِلْمٌ"}, "correct": 2}, {"question": "Which word has Tanween Kasrah (ـٍ)?", "hint": "Tanween Kasrah is two strokes below the last letter:", "hintArabic": "ـٍ", "options": []string{"نُورًا", "نُورٍ", "نُورٌ"}, "correct": 1}}}},
		},

		// ───────── LEVELS 11-15: Joining Letters & First Quran Words ─────────
		{
			ID:           11,
			Title:        "Letters Connect",
			Theme:        "Joining Arabic Letters",
			Goal:         "See how letters change shape when joined",
			Difficulty:   LevelMedium,
			XPReward:     150,
			UnlockReward: "badge:connector",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Letter Forms", Description: "One letter, four shapes", ScreenType: ScreenAction, Component: "LetterFormsComponent", Data: map[string]any{"letter": "ب", "forms": map[string]any{"isolated": "ب", "initial": "بـ", "medial": "ـبـ", "final": "ـب"}}},
				{Type: LessonQaida, Title: "Non-Connecting Letters", Description: "Six letters never join the next", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ا", "name": "أَلِف"}, {"letter": "د", "name": "دَال"}, {"letter": "ذ", "name": "ذَال"}, {"letter": "ر", "name": "رَاء"}, {"letter": "ز", "name": "زَاي"}, {"letter": "و", "name": "وَاو"}}, "note": "هذِهِ الحُرُوف لا تَتَّصِل بِما بَعْدَها"}},
				{Type: LessonQuiz, Title: "Does it Connect?", Description: "True or false", ScreenType: ScreenQuiz, Component: "TrueFalseComponent", Data: map[string]any{"rounds": []map[string]any{{"prompt": "This letter connects to the letter after it", "arabic": "ب", "answer": true}, {"prompt": "This letter connects to the letter after it", "arabic": "ر", "answer": false}, {"prompt": "This letter connects to the letter after it", "arabic": "د", "answer": false}, {"prompt": "This letter connects to the letter after it", "arabic": "ن", "answer": true}}}},
				{Type: LessonQaida, Title: "Connect to Form", Description: "Arrange the letters to form a word", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the letters — one tile is a decoy", "parts": []string{"ب", "س", "م"}, "distractors": []string{"ت"}, "meaning": "Forms: بِسْم"}},
				{Type: LessonQaida, Title: "Match the Final Form", Description: "Match isolated to final form", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its final form", "pairs": []map[string]any{{"left": "ب", "right": "ـب"}, {"left": "ت", "right": "ـت"}, {"left": "ن", "right": "ـن"}, {"left": "م", "right": "ـم"}}}},
				{Type: LessonQuiz, Title: "Which Won't Connect?", Description: "Spot the non-connecting letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which letter does NOT connect to the next letter?", "options": []string{"ب", "ت", "ر", "ن"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Connect letters to form each word", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"ك", "ت", "ب"}, "word": "كَتَب", "meaning": "He wrote"}, {"parts": []string{"ع", "ل", "م"}, "word": "عِلْم", "meaning": "Knowledge"}}}},
		},
		{
			ID:           12,
			Title:        "Simple Quran Words",
			Theme:        "First Quran Reading",
			Goal:         "Read words that appear often in the Quran",
			Difficulty:   LevelMedium,
			XPReward:     160,
			UnlockReward: "title:quran_beginner",
			Lessons: []Lesson{
				{Type: LessonPronunciation, Title: "Allah & Rabb", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "اللَّه"}, {"arabic": "رَبّ"}}}},
				{Type: LessonPronunciation, Title: "More Quran Words", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "نُور"}, {"arabic": "عِلْم"}, {"arabic": "حَقّ"}}}},
				{Type: LessonQuiz, Title: "Lightning Meanings", Description: "Quick! Match the meanings", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 7, "questions": []map[string]any{{"question": "Which word means 'Light'?", "options": []string{"نُور", "عِلْم", "حَقّ"}, "correct": 0}, {"question": "Which word means 'Knowledge'?", "options": []string{"نُور", "عِلْم", "رَبّ"}, "correct": 1}, {"question": "Which word means 'Lord'?", "options": []string{"حَقّ", "نُور", "رَبّ"}, "correct": 2}, {"question": "Which word means 'Truth'?", "options": []string{"حَقّ", "عِلْم", "نُور"}, "correct": 0}}}},
				{Type: LessonQaida, Title: "Complete the Phrase", Description: "Fill in the missing word", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the phrase", "sentence": []map[string]any{{"text": "بِسْمِ"}, {"blank": true, "answer": "اللَّهِ"}}, "bank": []string{"اللَّهِ", "رَبِّ", "نُورِ"}, "meaning": "In the name of Allah"}},
				{Type: LessonManners, Title: "Gratitude", Description: "Always be thankful", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Say الْحَمْدُ لِلَّه for every blessing", "Thank people who help you", "Be grateful for small things", "Gratitude increases blessings (Quran 14:7)"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Match each Quran word to its meaning", Data: map[string]any{"questions": []map[string]any{{"question": "Which word means 'Knowledge'?", "options": []string{"نُور", "عِلْم", "حَقّ"}, "correct": 1}, {"question": "Which word means 'Lord'?", "options": []string{"رَبّ", "نُور", "حَقّ"}, "correct": 0}}}},
		},
		{
			ID:           13,
			Title:        "Madd Basics",
			Theme:        "Elongation Rules",
			Goal:         "Learn the three Madd letters that stretch the sound",
			Difficulty:   LevelMedium,
			XPReward:     160,
			UnlockReward: "badge:tajweed_starter",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Madd?", Description: "Stretching the sound", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مَا", "name": "المَدّ بِالأَلِف", "note": "حُرُوف المَدّ: ا و ي"}},
				{Type: LessonPronunciation, Title: "Madd with Alif", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "قَالَ"}, {"arabic": "بَابْ"}, {"arabic": "نَارْ"}}}},
				{Type: LessonPronunciation, Title: "Madd with Waaw & Yaa", Description: "Tap each word to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "نُورْ"}, {"arabic": "يَقُولُ"}, {"arabic": "دِينْ"}}}},
				{Type: LessonQuiz, Title: "Madd or No Madd?", Description: "Does the sound stretch?", ScreenType: ScreenQuiz, Component: "TrueFalseComponent", Data: map[string]any{"rounds": []map[string]any{{"prompt": "This word has a Madd (stretched sound)", "arabic": "قَالَ", "answer": true}, {"prompt": "This word has a Madd", "arabic": "قُلْ", "answer": false}, {"prompt": "This word has a Madd", "arabic": "نُور", "answer": true}, {"prompt": "This word has a Madd", "arabic": "هَلْ", "answer": false}}}},
				{Type: LessonQuiz, Title: "Find the Madd", Description: "Which letter stretches the sound?", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which letter causes the Madd in قَالَ?", "options": []string{"ق", "ا", "ل"}, "correct": 1}},
				{Type: LessonHadith, Title: "Respect Parents", Description: "The pleasure of Allah", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The pleasure of Allah lies in the pleasure of the parents.", "reference": "Tirmidhi"}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen and choose the word with elongation", Data: map[string]any{"questions": []map[string]any{{"audio": "قَالَ", "options": []string{"قَالَ", "قُلْ", "قِيلَ"}, "correct": 0}, {"audio": "نُورْ", "options": []string{"نُورْ", "نَارْ", "نَهْر"}, "correct": 0}}}},
		},
		{
			ID:           14,
			Title:        "Sunnah Lifestyle",
			Theme:        "Daily Sunnah Habits",
			Goal:         "Learn daily sunnah habits and review your duas",
			Difficulty:   LevelMedium,
			XPReward:     140,
			UnlockReward: "badge:sunnah_follower",
			Lessons: []Lesson{
				{Type: LessonManners, Title: "Morning Sunnahs", Description: "Start your day beautifully", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Wake up and say the morning dua", "Use the مِسْوَاك to clean your teeth", "Pray Fajr on time", "Read the morning أَذْكَار"}}},
				{Type: LessonManners, Title: "Evening Sunnahs", Description: "End your day with barakah", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Read the evening أَذْكَار before sunset", "Pray Isha and Witr", "Recite آيَة الكُرْسِي before bed", "Sleep on your right side"}}},
				{Type: LessonManners, Title: "Patience (Sabr)", Description: "Reflect on patience", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "When do you find it hardest to be patient?", "options": []string{"When someone is rude to me", "When things don't go my way", "When I have to wait", "When I'm tired or hungry"}}},
				{Type: LessonRevision, Title: "Phrase Meaning", Description: "Choose the correct meaning", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which phrase means 'All praise is for Allah'?", "options": []string{"الْحَمْدُ لِلَّهِ", "سُبْحَانَ اللَّهِ", "اللَّهُ أَكْبَر"}, "correct": 0}},
				{Type: LessonDua, Title: "Dua Checklist", Description: "Tick off the duas you know", ScreenType: ScreenChecklist, Component: "PrayerChecklistComponent", Data: map[string]any{"steps": []string{"Before eating — بِسْمِ اللَّهِ", "After eating — الْحَمْدُ لِلَّهِ", "Before sleep dua", "Waking up dua", "Entering home dua", "Leaving home dua"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Test your daily sunnah knowledge", Data: map[string]any{"questions": []map[string]any{{"question": "What do you say before eating?", "options": []string{"بِسْمِ اللَّهِ", "الْحَمْدُ لِلَّهِ", "سُبْحَانَ اللَّهِ"}, "correct": 0}, {"question": "On which side should you sleep?", "options": []string{"Right", "Left", "Back"}, "correct": 0}}}},
		},
		{
			ID:           15,
			Title:        "Checkpoint Alpha",
			Theme:        "Mid-Journey Revision",
			Goal:         "Review everything you have learned so far",
			Difficulty:   LevelMedium,
			XPReward:     200,
			UnlockReward: "badge:checkpoint_hero",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Letters Review", Description: "Match letters to their names", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each letter to its name", "pairs": []map[string]any{{"left": "خ", "right": "خَاء"}, {"left": "ع", "right": "عَين"}, {"left": "ص", "right": "صَاد"}, {"left": "ط", "right": "طَاء"}}}},
				{Type: LessonRevision, Title: "Harakat Sort", Description: "Sort by harakat", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each letter by its harakat", "buckets": []string{"فَتْحَة", "كَسْرَة"}, "items": []map[string]any{{"text": "بَ", "bucket": 0}, {"text": "تِ", "bucket": 1}, {"text": "سَ", "bucket": 0}, {"text": "مِ", "bucket": 1}}}},
				{Type: LessonRevision, Title: "Lightning Revision", Description: "Everything so far — beat the clock!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 7, "questions": []map[string]any{{"question": "Which word has Tanween Fathah (ـً)?", "options": []string{"عِلْمٌ", "عِلْمٍ", "عِلْمًا"}, "correct": 2}, {"question": "Tap the letter صَاد", "options": []string{"س", "ص", "ض"}, "correct": 1}, {"question": "Which letter does NOT connect to the next?", "options": []string{"ب", "و", "ن"}, "correct": 1}, {"question": "Which word means 'from'?", "options": []string{"مِنْ", "مَنْ", "هَلْ"}, "correct": 0}}}},
				{Type: LessonRevision, Title: "Build the Phrase", Description: "Arrange the words in order", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the phrase", "parts": []string{"بِسْمِ", "اللَّهِ"}, "meaning": "In the name of Allah"}},
				{Type: LessonRevision, Title: "Complete the Word", Description: "Fill the missing harakat", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the word", "sentence": []map[string]any{{"text": "نَ"}, {"text": "صَ"}, {"blank": true, "answer": "رَ"}}, "bank": []string{"رَ", "رِ", "رُ"}, "meaning": "He helped"}},
				{Type: LessonRevision, Title: "Hadith Recall", Description: "Which one stayed with you?", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "Which hadith resonated with you the most?", "options": []string{"Actions are judged by intentions", "Cleanliness is half of faith", "Smiling is charity", "Truthfulness leads to Paradise"}}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "🎁 Treasure! Match each phrase to its name", Data: map[string]any{"pairs": []map[string]any{{"left": "بِسْمِ اللَّه", "right": "التَّسْمِيَة"}, {"left": "الْحَمْدُ لِلَّه", "right": "الحَمْدَلَة"}, {"left": "سُبْحَانَ اللَّه", "right": "التَّسْبِيح"}, {"left": "اللَّهُ أَكْبَر", "right": "التَّكْبِير"}}}},
		},

		// ───────── LEVELS 16-20: Quran Reading & Graduation ─────────
		{
			ID:           16,
			Title:        "Al-Fatihah Prep",
			Theme:        "Reading Surah Al-Fatihah",
			Goal:         "Begin reading Surah Al-Fatihah",
			Difficulty:   LevelHard,
			XPReward:     200,
			UnlockReward: "title:quran_reader",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Bismillah Complete", Description: "Read the full Bismillah", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Fatihah", "text": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", "meaning": "In the name of Allah, the Most Gracious, the Most Merciful"}},
				{Type: LessonQaida, Title: "Shaddah", Description: "It doubles the letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "الرَّحْمَٰن", "name": "الشَّدَّة", "note": "الشَّدَّة تُشَدِّد الحَرْف"}},
				{Type: LessonQaida, Title: "Build the Ayah", Description: "Arrange the words of ayah 2", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the words of the ayah — one word is a decoy", "parts": []string{"الْحَمْدُ", "لِلَّهِ", "رَبِّ", "الْعَالَمِينَ"}, "distractors": []string{"الرَّحِيمِ"}, "meaning": "All praise is for Allah, Lord of the worlds"}},
				{Type: LessonQaida, Title: "Complete the Ayah", Description: "Fill in the missing word", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the Bismillah", "sentence": []map[string]any{{"text": "بِسْمِ"}, {"text": "اللَّهِ"}, {"blank": true, "answer": "الرَّحْمَٰنِ"}, {"text": "الرَّحِيمِ"}}, "bank": []string{"الرَّحْمَٰنِ", "الْعَالَمِينَ", "الرَّحِيمِ"}, "meaning": "In the name of Allah, the Most Gracious, the Most Merciful"}},
				{Type: LessonQuiz, Title: "Meaning Check", Description: "Choose the correct meaning", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What does الرَّحْمَٰن mean?", "options": []string{"The Most Gracious", "The Lord", "The Creator"}, "correct": 0}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen and choose each word of Al-Fatihah", Data: map[string]any{"questions": []map[string]any{{"audio": "بِسْمِ", "options": []string{"بِسْمِ", "نِسْمِ", "بِشْمِ"}, "correct": 0}, {"audio": "اللَّهِ", "options": []string{"اللَّهِ", "اللَحِ", "الْلَهِ"}, "correct": 0}}}},
		},
		{
			ID:           17,
			Title:        "Tajweed Essentials",
			Theme:        "Basic Tajweed Rules",
			Goal:         "Learn Idghaam, Ikhfaa, and Qalqalah",
			Difficulty:   LevelHard,
			XPReward:     220,
			UnlockReward: "badge:tajweed_student",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Ikhfaa", Description: "The hidden Noon", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مِنْ بَعْدِ", "name": "الإِخْفَاء", "note": "النُّون تُخْفَى قَبْلَ الباء"}},
				{Type: LessonQaida, Title: "Idghaam", Description: "The merging Noon", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مِنْ رَبِّ", "name": "الإِدْغَام", "note": "النُّون تُدْغَم في الراء"}},
				{Type: LessonQaida, Title: "Qalqalah", Description: "The bouncing letters", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "قُطْبُ جَدٍّ", "name": "القَلْقَلَة", "note": "حُرُوف القَلْقَلَة: ق ط ب ج د"}},
				{Type: LessonQaida, Title: "Match the Rule", Description: "Match each phrase to its rule", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each phrase to its tajweed rule", "pairs": []map[string]any{{"left": "مِنْ رَبِّ", "right": "إِدْغَام"}, {"left": "مِنْ بَعْدِ", "right": "إِخْفَاء"}, {"left": "أَحَدْ", "right": "قَلْقَلَة"}}}},
				{Type: LessonQaida, Title: "Sort the Rules", Description: "Idghaam or Ikhfaa?", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each phrase by its tajweed rule", "hint": "Idghaam = the Noon merges into the next letter. Ikhfaa = the Noon is hidden with a nasal sound. Idghaam letters:", "hintArabic": "يَرْمَلُون", "buckets": []string{"إِدْغَام", "إِخْفَاء"}, "items": []map[string]any{{"text": "مِنْ رَبِّ", "bucket": 0}, {"text": "مِنْ قَبْلُ", "bucket": 1}, {"text": "مِنْ وَلِيّ", "bucket": 0}, {"text": "أَنتُمْ", "bucket": 1}}}},
				{Type: LessonQuiz, Title: "Tajweed Check", Description: "Choose the correct rule", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What happens to Noon Sakin before ر?", "hint": "ر is one of the letters the Noon merges into:", "hintArabic": "يَرْمَلُون", "options": []string{"إِدْغَام", "إِخْفَاء", "إِظْهَار"}, "correct": 0}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Identify the tajweed rule in each phrase", Data: map[string]any{"questions": []map[string]any{{"question": "Which rule applies in مِنْ رَبِّ?", "hint": "The Noon of مِنْ merges into the ر right after it.", "options": []string{"إِدْغَام", "إِخْفَاء", "قَلْقَلَة"}, "correct": 0}, {"question": "Which rule applies in أَحَدْ?", "hint": "The last letter carries a sukoon and bounces with an echo. Qalqalah letters:", "hintArabic": "قُطْبُ جَدّ", "options": []string{"قَلْقَلَة", "إِدْغَام", "مَدّ"}, "correct": 0}}}},
		},
		{
			ID:           18,
			Title:        "Short Surahs",
			Theme:        "Reading Complete Surahs",
			Goal:         "Read Surah Al-Ikhlas and Al-Falaq",
			Difficulty:   LevelHard,
			XPReward:     230,
			UnlockReward: "title:surah_scholar",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Surah Al-Ikhlas", Description: "Read the complete surah", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Ikhlas (112)", "text": "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", "meaning": "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent."}},
				{Type: LessonQaida, Title: "Build Ayah 1", Description: "Arrange the first ayah of Al-Ikhlas", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the ayah — one word is a decoy", "parts": []string{"قُلْ", "هُوَ", "اللَّهُ", "أَحَدٌ"}, "distractors": []string{"الصَّمَدُ"}, "meaning": "Say: He is Allah, the One"}},
				{Type: LessonQaida, Title: "Build Al-Falaq", Description: "Arrange the first ayah of Al-Falaq", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the ayah — one word is a decoy", "parts": []string{"قُلْ", "أَعُوذُ", "بِرَبِّ", "الْفَلَقِ"}, "distractors": []string{"النَّاسِ"}, "meaning": "Say: I seek refuge in the Lord of daybreak"}},
				{Type: LessonQuiz, Title: "Understanding", Description: "Choose the correct answer", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What is the main message of Surah Al-Ikhlas?", "options": []string{"The Oneness of Allah", "Stories of the prophets", "The Day of Judgment"}, "correct": 0}},
				{Type: LessonManners, Title: "Character Building", Description: "Reflect on your character", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "Which trait would you like to develop most?", "options": []string{"Honesty (صِدْق)", "Patience (صَبْر)", "Gratitude (شُكْر)", "Generosity (كَرَم)"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Answer questions about the surahs", Data: map[string]any{"questions": []map[string]any{{"question": "How many ayahs are in Al-Ikhlas?", "options": []string{"3", "4", "5"}, "correct": 1}, {"question": "What does الصَّمَد mean?", "options": []string{"The Eternal Refuge", "The One", "The Creator"}, "correct": 0}}}},
		},
		{
			ID:           19,
			Title:        "Confidence Builder",
			Theme:        "Fluent Reading Practice",
			Goal:         "Read longer phrases with confidence",
			Difficulty:   LevelHard,
			XPReward:     250,
			UnlockReward: "badge:confident_reader",
			Lessons: []Lesson{
				{Type: LessonPronunciation, Title: "Read Smoothly", Description: "Tap each phrase to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "الْحَمْدُ لِلَّهِ"}, {"arabic": "سُبْحَانَ اللَّهِ"}, {"arabic": "لَا إِلَٰهَ إِلَّا اللَّه"}}}},
				{Type: LessonQaida, Title: "Build Ayatul Kursi", Description: "Arrange the opening words", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the opening of Ayatul Kursi — one word is a decoy", "parts": []string{"اللَّهُ", "لَا", "إِلَٰهَ", "إِلَّا", "هُوَ"}, "distractors": []string{"نُورٌ"}, "meaning": "Allah — there is no deity except Him"}},
				{Type: LessonQaida, Title: "Complete the Ayah", Description: "Fill in the missing name", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the ayah", "sentence": []map[string]any{{"text": "الْحَيُّ"}, {"blank": true, "answer": "الْقَيُّومُ"}}, "bank": []string{"الْقَيُّومُ", "الرَّحِيمُ", "الْعَلِيمُ"}, "meaning": "The Ever-Living, the Sustainer of existence"}},
				{Type: LessonRevision, Title: "Word Hunt", Description: "Find the name of Allah", ScreenType: ScreenAction, Component: "LetterHuntComponent", Data: map[string]any{"instruction": "Tap every اللَّهُ", "target": "اللَّهُ", "grid": []string{"اللَّهُ", "إِلَٰهَ", "لِلَّهِ", "اللَّهُ", "إِلَّا", "اللَّهُ", "لَهُ", "بِاللَّهِ"}}},
				{Type: LessonRevision, Title: "Makharij", Description: "Where letters come from", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Throat letters: ع غ ح خ ه ء", "Lip letters: ب م و ف", "Practice each group slowly", "Clear makharij makes clear recitation"}}},
				{Type: LessonHadith, Title: "Reward of Reading", Description: "Every letter is rewarded", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Whoever reads a letter from the Book of Allah will have a reward, multiplied by ten.", "reference": "Tirmidhi"}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen and choose the phrase you heard", Data: map[string]any{"questions": []map[string]any{{"audio": "الْحَمْدُ لِلَّهِ", "options": []string{"الْحَمْدُ لِلَّهِ", "سُبْحَانَ اللَّهِ", "اللَّهُ أَكْبَر"}, "correct": 0}, {"audio": "لَا إِلَٰهَ إِلَّا اللَّه", "options": []string{"لَا إِلَٰهَ إِلَّا اللَّه", "سُبْحَانَ اللَّهِ", "الْحَمْدُ لِلَّهِ"}, "correct": 0}}}},
		},
		{
			ID:           20,
			Title:        "Beginner Graduation!",
			Theme:        "Final Assessment & Celebration",
			Goal:         "Pass the final test and earn your Qaida Certificate!",
			Difficulty:   LevelHard,
			XPReward:     300,
			UnlockReward: "badge:qaida_graduate",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Final Test: Letters", Description: "Identify the letter", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which name belongs to this letter — غ?", "options": []string{"عَين", "غَين", "فَاء", "قَاف"}, "correct": 1}},
				{Type: LessonRevision, Title: "Final Test: Reading", Description: "Arrange the graduation ayah", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the ayah", "parts": []string{"إِنَّا", "أَعْطَيْنَاكَ", "الْكَوْثَرَ"}, "meaning": "Indeed, We have granted you Al-Kawthar"}},
				{Type: LessonRevision, Title: "Final Test: Harakat", Description: "Choose the correct ending", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which word has Tanween Dammah (ـٌ)?", "options": []string{"مُسْلِمٌ", "مُسْلِمًا", "مُسْلِمٍ"}, "correct": 0}},
				{Type: LessonRevision, Title: "Final Test: Tajweed", Description: "Identify the rule", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which tajweed rule is in إِنَّا?", "options": []string{"غُنَّة", "قَلْقَلَة", "مَدّ"}, "correct": 0}},
				{Type: LessonRevision, Title: "Final Lightning Test", Description: "Everything you learned — fast!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 8, "questions": []map[string]any{{"question": "Tap the letter غَين", "options": []string{"ع", "غ", "ف"}, "correct": 1}, {"question": "Which word has Tanween Kasrah (ـٍ)?", "options": []string{"نُورًا", "نُورٍ", "نُورٌ"}, "correct": 1}, {"question": "Which letter has a Fathah?", "options": []string{"مِ", "مُ", "مَ"}, "correct": 2}, {"question": "Which word has a Madd?", "options": []string{"قَالَ", "قُلْ", "هَلْ"}, "correct": 0}, {"question": "Which rule is in مِنْ رَبِّ?", "options": []string{"إِدْغَام", "إِخْفَاء", "قَلْقَلَة"}, "correct": 0}}}},
				{Type: LessonRevision, Title: "Certificate Ceremony", Description: "Congratulations, graduate!", ScreenType: ScreenAction, Component: "CertificateComponent", Data: map[string]any{"title": "Qaida Graduate", "message": "MashaAllah! You can now recognise every Arabic letter, read with harakat and tanween, understand basic tajweed, and read short Quran ayahs. Your journey to fluent Quran reading has truly begun!", "next_phase": "Phase 3: Learn to Pray"}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Grand Treasure! Match each phrase to its name", Data: map[string]any{"pairs": []map[string]any{{"left": "بِسْمِ اللَّه", "right": "التَّسْمِيَة"}, {"left": "الْحَمْدُ لِلَّه", "right": "الحَمْدَلَة"}, {"left": "سُبْحَانَ اللَّه", "right": "التَّسْبِيح"}, {"left": "اللَّهُ أَكْبَر", "right": "التَّكْبِير"}, {"left": "لَا إِلَٰهَ إِلَّا اللَّه", "right": "التَّهْلِيل"}, {"left": "أَسْتَغْفِرُ اللَّه", "right": "الاسْتِغْفَار"}}}},
		},

		// ───────── LEVELS 21-30: Learn to Pray (Salah) ─────────
		{
			ID:           21,
			Title:        "Wudu Step by Step",
			Theme:        "Purification Before Prayer",
			Goal:         "Learn how to make wudu before you pray",
			Difficulty:   LevelMedium,
			XPReward:     200,
			UnlockReward: "badge:purified",
			Lessons: []Lesson{
				{Type: LessonManners, Title: "Why Wudu?", Description: "Purity is the key to prayer", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Wudu is required before every prayer", "It washes away small sins, as the Prophet ﷺ taught", "Begin with the intention (niyyah) in your heart", "Then say بِسْمِ اللَّه before you start"}}},
				{Type: LessonQaida, Title: "The Wudu Steps", Description: "Follow the steps in order", ScreenType: ScreenChecklist, Component: "PrayerChecklistComponent", Data: map[string]any{"steps": []string{"Make the intention in your heart", "Say بِسْمِ اللَّه", "Wash both hands 3 times", "Rinse the mouth 3 times", "Sniff water into the nose 3 times", "Wash the face 3 times", "Wash both arms to the elbows 3 times", "Wipe the head and the ears once", "Wash both feet to the ankles 3 times"}}},
				{Type: LessonDua, Title: "Dua After Wudu", Description: "Say this when you finish", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", "meaning": "I bear witness that there is no god but Allah, and that Muhammad is His servant and Messenger", "context": "Say this after completing your wudu"}},
				{Type: LessonQuiz, Title: "How Many Times?", Description: "Choose the correct number", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How many times do you wash your face in wudu?", "options": []string{"Once", "Twice", "Three times"}, "correct": 2}},
				{Type: LessonQuiz, Title: "How Do You Begin?", Description: "Choose what you say first", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What do you say as you begin wudu?", "options": []string{"بِسْمِ اللَّه", "اللَّهُ أَكْبَر", "سُبْحَانَ اللَّه"}, "correct": 0}},
				{Type: LessonManners, Title: "Feeling Fresh", Description: "Reflect on purity", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "How do you feel after making wudu?", "options": []string{"Clean and calm", "Ready to pray", "Close to Allah", "Refreshed"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Test your wudu knowledge", Data: map[string]any{"questions": []map[string]any{{"question": "What is the FIRST step of wudu?", "options": []string{"The intention (niyyah)", "Washing the feet", "Wiping the head"}, "correct": 0}, {"question": "How many times do you wash your arms?", "options": []string{"Once", "Three times", "Five times"}, "correct": 1}}}},
		},
		{
			ID:           22,
			Title:        "Standing & Takbir",
			Theme:        "Starting the Prayer",
			Goal:         "Begin salah with the Takbir and the opening dua",
			Difficulty:   LevelMedium,
			XPReward:     210,
			UnlockReward: "badge:takbir",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Takbiratul Ihram", Description: "The prayer begins here", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "اللَّهُ أَكْبَر", "name": "تَكْبِيرَة الإِحْرَام", "note": "تَرْفَع يَدَيْكَ وَتَقُول اللَّهُ أَكْبَر"}},
				{Type: LessonDua, Title: "The Opening Dua", Description: "Say this quietly after the Takbir", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ", "meaning": "Glory and praise be to You, O Allah. Blessed is Your name, exalted is Your majesty, and there is no god but You", "context": "Recite silently right after the opening Takbir"}},
				{Type: LessonQaida, Title: "Build the Takbir", Description: "Arrange the words", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the opening Takbir", "parts": []string{"اللَّهُ", "أَكْبَر"}, "meaning": "Allah is the Greatest"}},
				{Type: LessonPronunciation, Title: "Before Al-Fatihah", Description: "Tap each to hear it", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ"}, {"arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"}}}},
				{Type: LessonQuiz, Title: "How to Start", Description: "Choose the opening words", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which words begin the prayer?", "options": []string{"اللَّهُ أَكْبَر", "السَّلَامُ عَلَيْكُم", "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, "correct": 0}},
				{Type: LessonHadith, Title: "Key to Prayer", Description: "A hadith on purity & prayer", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The key to Paradise is prayer, and the key to prayer is purification.", "reference": "Tirmidhi"}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen and choose what you heard", Data: map[string]any{"questions": []map[string]any{{"audio": "اللَّهُ أَكْبَر", "options": []string{"اللَّهُ أَكْبَر", "سُبْحَانَ اللَّه", "الْحَمْدُ لِلَّه"}, "correct": 0}, {"audio": "أَعُوذُ بِاللَّه", "options": []string{"أَعُوذُ بِاللَّه", "بِسْمِ اللَّه", "اللَّهُ أَكْبَر"}, "correct": 0}}}},
		},
		{
			ID:           23,
			Title:        "Reciting Al-Fatihah",
			Theme:        "The Heart of Every Rak'ah",
			Goal:         "Recite Surah Al-Fatihah in your prayer",
			Difficulty:   LevelMedium,
			XPReward:     220,
			UnlockReward: "title:fatihah_reciter",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Surah Al-Fatihah", Description: "Read the full surah", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Fatihah (1)", "text": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", "meaning": "All praise is for Allah, Lord of all worlds; the Most Gracious, the Most Merciful; Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those You have blessed, not of those who earned anger, nor of those who went astray."}},
				{Type: LessonQaida, Title: "Build the Ayah", Description: "Arrange the words in order", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Arrange the ayah — one word is a decoy", "parts": []string{"إِيَّاكَ", "نَعْبُدُ", "وَإِيَّاكَ", "نَسْتَعِينُ"}, "distractors": []string{"الْعَالَمِينَ"}, "meaning": "You alone we worship, and You alone we ask for help"}},
				{Type: LessonQuiz, Title: "Complete the Ayah", Description: "Fill in the missing word", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the ayah", "sentence": []map[string]any{{"text": "اهْدِنَا"}, {"text": "الصِّرَاطَ"}, {"blank": true, "answer": "الْمُسْتَقِيمَ"}}, "bank": []string{"الْمُسْتَقِيمَ", "الْعَالَمِينَ", "الرَّحِيمَ"}, "meaning": "Guide us to the straight path"}},
				{Type: LessonQuiz, Title: "After Al-Fatihah", Description: "Choose the correct answer", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What do you say after finishing Al-Fatihah?", "options": []string{"آمِين", "اللَّهُ أَكْبَر", "السَّلَامُ عَلَيْكُم"}, "correct": 0}},
				{Type: LessonRevision, Title: "Match the Meaning", Description: "Match each phrase to its meaning", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each phrase to its meaning", "pairs": []map[string]any{{"left": "الْحَمْدُ لِلَّهِ", "right": "All praise is for Allah"}, {"left": "رَبِّ الْعَالَمِينَ", "right": "Lord of the worlds"}, {"left": "مَالِكِ يَوْمِ الدِّينِ", "right": "Master of the Day of Judgment"}}}},
				{Type: LessonManners, Title: "Pray with Focus", Description: "Tips for khushu'", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Stand still and look at the place of sujood", "Try to understand the words you recite", "Pray as if you can see Allah", "Remember Allah sees you even if you cannot see Him"}}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Build each phrase of Al-Fatihah", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"مَالِكِ", "يَوْمِ", "الدِّينِ"}, "word": "مَالِكِ يَوْمِ الدِّينِ", "meaning": "Master of the Day of Judgment"}, {"parts": []string{"إِيَّاكَ", "نَعْبُدُ"}, "word": "إِيَّاكَ نَعْبُدُ", "meaning": "You alone we worship"}}}},
		},
		{
			ID:           24,
			Title:        "Ruku' & its Tasbih",
			Theme:        "Bowing Before Allah",
			Goal:         "Learn the bowing position and what to say in it",
			Difficulty:   LevelMedium,
			XPReward:     230,
			UnlockReward: "badge:ruku",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Ruku'?", Description: "The bowing of prayer", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "رُكُوع", "name": "الرُّكُوع", "note": "تَنْحَنِي وَتَضَع يَدَيْكَ عَلَى رُكْبَتَيْك"}},
				{Type: LessonDua, Title: "Tasbih of Ruku'", Description: "Say this 3 times while bowing", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "سُبْحَانَ رَبِّيَ الْعَظِيم", "meaning": "Glory be to my Lord, the Most Great", "context": "Repeat 3 times while bowing in ruku'"}},
				{Type: LessonDua, Title: "Rising from Ruku'", Description: "Say this as you stand", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْد", "meaning": "Allah hears the one who praises Him; our Lord, to You is all praise", "context": "Say as you rise up straight from ruku'"}},
				{Type: LessonQuiz, Title: "How Many Times?", Description: "Choose the correct number", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How many times do you say the tasbih in ruku'?", "options": []string{"Once", "Three times", "Seven times"}, "correct": 1}},
				{Type: LessonQuiz, Title: "Complete the Tasbih", Description: "Fill in the missing word", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the tasbih of ruku'", "sentence": []map[string]any{{"text": "سُبْحَانَ"}, {"text": "رَبِّيَ"}, {"blank": true, "answer": "الْعَظِيم"}}, "bank": []string{"الْعَظِيم", "الْأَعْلَى", "الْكَرِيم"}, "meaning": "Glory be to my Lord, the Most Great"}},
				{Type: LessonManners, Title: "Humility", Description: "Reflect on bowing", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "What does bowing in ruku' remind you of?", "options": []string{"Allah's greatness", "My humility before Him", "Gratitude to Allah", "Submission to Allah"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Test what you say in ruku'", Data: map[string]any{"questions": []map[string]any{{"question": "Which tasbih is said in ruku'?", "hint": "الْعَظِيم means 'the Most Great'", "options": []string{"سُبْحَانَ رَبِّيَ الْعَظِيم", "سُبْحَانَ رَبِّيَ الْأَعْلَى", "رَبِّ اغْفِرْ لِي"}, "correct": 0}, {"question": "What do you say rising from ruku'?", "options": []string{"سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ", "اللَّهُ أَكْبَر", "آمِين"}, "correct": 0}}}},
		},
		{
			ID:           25,
			Title:        "Sujood & Sitting",
			Theme:        "Closest to Allah",
			Goal:         "Learn prostration and the sitting between sujood",
			Difficulty:   LevelHard,
			XPReward:     250,
			UnlockReward: "badge:sujood",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Sujood?", Description: "Prostration on seven parts", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "سُجُود", "name": "السُّجُود", "note": "تَسْجُد عَلَى سَبْعَةِ أَعْضَاء: الجَبْهَة وَالأَنْف وَاليَدَيْن وَالرُّكْبَتَيْن وَأَطْرَاف القَدَمَيْن"}},
				{Type: LessonDua, Title: "Tasbih of Sujood", Description: "Say this 3 times in sujood", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "سُبْحَانَ رَبِّيَ الْأَعْلَى", "meaning": "Glory be to my Lord, the Most High", "context": "Repeat 3 times while in prostration"}},
				{Type: LessonDua, Title: "Between the Sujood", Description: "Say this while sitting", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "رَبِّ اغْفِرْ لِي", "meaning": "My Lord, forgive me", "context": "Say while sitting between the two prostrations"}},
				{Type: LessonQuiz, Title: "Which Tasbih?", Description: "Choose the sujood tasbih", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "Which tasbih is said in sujood?", "hint": "In sujood you are lowest, praising the Highest:", "hintArabic": "الْأَعْلَى", "options": []string{"سُبْحَانَ رَبِّيَ الْأَعْلَى", "سُبْحَانَ رَبِّيَ الْعَظِيم", "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ"}, "correct": 0}},
				{Type: LessonQuiz, Title: "True or False?", Description: "Check your knowledge", ScreenType: ScreenQuiz, Component: "TrueFalseComponent", Data: map[string]any{"rounds": []map[string]any{{"prompt": "This is said in sujood", "arabic": "سُبْحَانَ رَبِّيَ الْأَعْلَى", "answer": true}, {"prompt": "This is said between the two sujood", "arabic": "رَبِّ اغْفِرْ لِي", "answer": true}, {"prompt": "This is said in sujood", "arabic": "سُبْحَانَ رَبِّيَ الْعَظِيم", "answer": false}}}},
				{Type: LessonHadith, Title: "The Closest Moment", Description: "A hadith on sujood", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The closest a servant is to his Lord is when he is in prostration, so make plenty of dua.", "reference": "Sahih Muslim"}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Treasure! Match each posture to what you say", Data: map[string]any{"pairs": []map[string]any{{"left": "الْقِيَام", "right": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ"}, {"left": "الرُّكُوع", "right": "سُبْحَانَ رَبِّيَ الْعَظِيم"}, {"left": "السُّجُود", "right": "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, {"left": "الْجُلُوس", "right": "رَبِّ اغْفِرْ لِي"}}}},
		},
		{
			ID:           26,
			Title:        "The Tashahhud",
			Theme:        "The Testimony in Sitting",
			Goal:         "Learn and build the Tashahhud",
			Difficulty:   LevelHard,
			XPReward:     260,
			UnlockReward: "title:tashahhud_learner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "At-Tahiyyat", Description: "Read the full Tashahhud", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "At-Tashahhud", "text": "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", "meaning": "All greetings, prayers and good deeds are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and Messenger."}},
				{Type: LessonQaida, Title: "Build the Shahadah", Description: "Arrange the testimony", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the testimony — one word is a decoy", "parts": []string{"أَشْهَدُ", "أَنْ", "لَا", "إِلَٰهَ", "إِلَّا", "اللَّهُ"}, "distractors": []string{"وَرَسُولُهُ"}, "meaning": "I bear witness that there is no god but Allah"}},
				{Type: LessonQuiz, Title: "Complete the Line", Description: "Fill in the missing word", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the Tashahhud", "sentence": []map[string]any{{"text": "السَّلَامُ"}, {"text": "عَلَيْكَ"}, {"text": "أَيُّهَا"}, {"blank": true, "answer": "النَّبِيُّ"}}, "bank": []string{"النَّبِيُّ", "الصَّالِحِينَ", "الرَّحِيمُ"}, "meaning": "Peace be upon you, O Prophet"}},
				{Type: LessonDua, Title: "Durood Sharif", Description: "Sending blessings on the Prophet ﷺ", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ", "meaning": "O Allah, send blessings upon Muhammad and upon the family of Muhammad", "context": "Recite after the Tashahhud in the final sitting"}},
				{Type: LessonQuiz, Title: "When to Recite?", Description: "Choose the correct answer", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "In which position do you recite the Tashahhud?", "options": []string{"While sitting", "While bowing", "While standing"}, "correct": 0}},
				{Type: LessonManners, Title: "Loving the Prophet ﷺ", Description: "Reflect on the Durood", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "Why do we send blessings on the Prophet ﷺ in every prayer?", "options": []string{"To show our love for him", "To follow his teaching", "To earn Allah's mercy", "To thank him for guiding us"}}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Build the testimony of faith", Data: map[string]any{"rounds": []map[string]any{{"parts": []string{"أَشْهَدُ", "أَنْ", "لَا", "إِلَٰهَ", "إِلَّا", "اللَّهُ"}, "word": "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ", "meaning": "I bear witness that there is no god but Allah"}}}},
		},
		{
			ID:           27,
			Title:        "Salam & Finishing",
			Theme:        "Completing the Prayer",
			Goal:         "End the prayer with Taslim and learn the adhkar after salah",
			Difficulty:   LevelMedium,
			XPReward:     240,
			UnlockReward: "badge:salam",
			Lessons: []Lesson{
				{Type: LessonDua, Title: "The Taslim", Description: "How the prayer ends", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّه", "meaning": "Peace and the mercy of Allah be upon you", "context": "Turn your face to the right, then the left, saying this to end the prayer"}},
				{Type: LessonQaida, Title: "One Rak'ah in Order", Description: "Follow the full rak'ah", ScreenType: ScreenChecklist, Component: "PrayerChecklistComponent", Data: map[string]any{"steps": []string{"Takbir — اللَّهُ أَكْبَر", "Recite Al-Fatihah", "Recite a short surah", "Ruku' — سُبْحَانَ رَبِّيَ الْعَظِيم", "Stand — سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ", "Sujood — سُبْحَانَ رَبِّيَ الْأَعْلَى", "Sit — رَبِّ اغْفِرْ لِي", "Second sujood — سُبْحَانَ رَبِّيَ الْأَعْلَى"}}},
				{Type: LessonDua, Title: "After the Prayer", Description: "An adhkar to say when you finish", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "أَسْتَغْفِرُ اللَّهَ، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَام", "meaning": "I seek Allah's forgiveness. O Allah, You are Peace and from You comes peace", "context": "Say after completing the prayer (seek forgiveness 3 times)"}},
				{Type: LessonQuiz, Title: "How to End", Description: "Choose the correct answer", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How do you end the prayer?", "options": []string{"With the Taslim (السَّلَامُ عَلَيْكُم)", "With the Takbir", "With Al-Fatihah"}, "correct": 0}},
				{Type: LessonRevision, Title: "Quick Recall", Description: "Beat the clock!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 8, "questions": []map[string]any{{"question": "What do you say in ruku'?", "options": []string{"سُبْحَانَ رَبِّيَ الْعَظِيم", "سُبْحَانَ رَبِّيَ الْأَعْلَى", "رَبِّ اغْفِرْ لِي"}, "correct": 0}, {"question": "What do you say in sujood?", "options": []string{"سُبْحَانَ رَبِّيَ الْأَعْلَى", "سُبْحَانَ رَبِّيَ الْعَظِيم", "آمِين"}, "correct": 0}, {"question": "What ends the prayer?", "options": []string{"السَّلَامُ عَلَيْكُم", "اللَّهُ أَكْبَر", "آمِين"}, "correct": 0}}}},
				{Type: LessonManners, Title: "After Salah", Description: "Sunnah adhkar to remember", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Say سُبْحَانَ اللَّه 33 times", "Say الْحَمْدُ لِلَّه 33 times", "Say اللَّهُ أَكْبَر 33 times", "Then recite آيَة الكُرْسِي for protection"}}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match each posture to what you say", Data: map[string]any{"pairs": []map[string]any{{"left": "الرُّكُوع", "right": "سُبْحَانَ رَبِّيَ الْعَظِيم"}, {"left": "السُّجُود", "right": "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, {"left": "الْجُلُوس", "right": "رَبِّ اغْفِرْ لِي"}, {"left": "نِهَايَة الصَّلَاة", "right": "السَّلَامُ عَلَيْكُم"}}}},
		},
		{
			ID:           28,
			Title:        "The Five Daily Prayers",
			Theme:        "When & How Many",
			Goal:         "Learn the five prayers and how many rak'ahs each has",
			Difficulty:   LevelMedium,
			XPReward:     240,
			UnlockReward: "badge:five_prayers",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "The Five Prayers", Description: "Five prayers, every day", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"الفَجْر — at dawn, before sunrise", "الظُّهْر — after midday", "العَصْر — in the afternoon", "المَغْرِب — just after sunset", "العِشَاء — at night"}}},
				{Type: LessonQaida, Title: "Match the Rak'ahs", Description: "How many fard rak'ahs?", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each prayer to its number of fard rak'ahs", "pairs": []map[string]any{{"left": "الفَجْر", "right": "٢"}, {"left": "المَغْرِب", "right": "٣"}, {"left": "الظُّهْر", "right": "٤"}, {"left": "العِشَاء", "right": "٤"}}}},
				{Type: LessonQuiz, Title: "Fajr Rak'ahs", Description: "Choose the correct number", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How many fard rak'ahs does Fajr have?", "options": []string{"٢", "٣", "٤"}, "correct": 0}},
				{Type: LessonQuiz, Title: "Sort by Rak'ahs", Description: "Two or four?", ScreenType: ScreenAction, Component: "SortBucketsComponent", Data: map[string]any{"instruction": "Sort each prayer by its number of fard rak'ahs", "hint": "Fajr is the short one; Dhuhr, Asr and Isha are the long ones.", "bucketHints": []string{"٢", "٤"}, "buckets": []string{"رَكْعَتَان", "أَرْبَع رَكَعَات"}, "items": []map[string]any{{"text": "الفَجْر", "bucket": 0}, {"text": "الظُّهْر", "bucket": 1}, {"text": "العَصْر", "bucket": 1}, {"text": "العِشَاء", "bucket": 1}}}},
				{Type: LessonRevision, Title: "Prayer Times", Description: "Beat the clock!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 8, "questions": []map[string]any{{"question": "Which prayer is at dawn?", "options": []string{"الفَجْر", "العِشَاء", "العَصْر"}, "correct": 0}, {"question": "Which prayer is just after sunset?", "options": []string{"المَغْرِب", "الظُّهْر", "الفَجْر"}, "correct": 0}, {"question": "How many fard rak'ahs in Maghrib?", "options": []string{"٣", "٢", "٤"}, "correct": 0}}}},
				{Type: LessonHadith, Title: "First to be Judged", Description: "A hadith on prayer", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The first thing a servant will be asked about on the Day of Judgment is the prayer.", "reference": "Tirmidhi"}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Test the five daily prayers", Data: map[string]any{"questions": []map[string]any{{"question": "How many fard prayers are there each day?", "options": []string{"Five", "Three", "Seven"}, "correct": 0}, {"question": "Which prayer has 3 rak'ahs?", "options": []string{"المَغْرِب", "الفَجْر", "العَصْر"}, "correct": 0}}}},
		},
		{
			ID:           29,
			Title:        "Checkpoint: A Full Rak'ah",
			Theme:        "Putting It Together",
			Goal:         "Revise everything you have learned about salah",
			Difficulty:   LevelHard,
			XPReward:     270,
			UnlockReward: "badge:salah_checkpoint",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Order of the Rak'ah", Description: "Walk through one rak'ah", ScreenType: ScreenChecklist, Component: "PrayerChecklistComponent", Data: map[string]any{"steps": []string{"Takbir — اللَّهُ أَكْبَر", "Al-Fatihah & a surah", "Ruku' with its tasbih", "Stand — سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ", "First sujood", "Sit — رَبِّ اغْفِرْ لِي", "Second sujood", "Tashahhud in the final sitting"}}},
				{Type: LessonRevision, Title: "Build the Phrase", Description: "Arrange the words", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build what you say rising from ruku'", "parts": []string{"سَمِعَ", "اللَّهُ", "لِمَنْ", "حَمِدَهُ"}, "meaning": "Allah hears the one who praises Him"}},
				{Type: LessonRevision, Title: "Lightning Revision", Description: "Everything so far — fast!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 7, "questions": []map[string]any{{"question": "Tasbih of ruku'?", "options": []string{"سُبْحَانَ رَبِّيَ الْعَظِيم", "سُبْحَانَ رَبِّيَ الْأَعْلَى", "رَبِّ اغْفِرْ لِي"}, "correct": 0}, {"question": "Tasbih of sujood?", "options": []string{"سُبْحَانَ رَبِّيَ الْأَعْلَى", "سُبْحَانَ رَبِّيَ الْعَظِيم", "آمِين"}, "correct": 0}, {"question": "How many rak'ahs in Fajr?", "options": []string{"٢", "٣", "٤"}, "correct": 0}, {"question": "What ends the prayer?", "options": []string{"السَّلَامُ عَلَيْكُم", "اللَّهُ أَكْبَر", "آمِين"}, "correct": 0}}}},
				{Type: LessonRevision, Title: "Match Posture & Saying", Description: "Match each one", ScreenType: ScreenAction, Component: "MatchPairsComponent", Data: map[string]any{"instruction": "Match each posture to what you say", "pairs": []map[string]any{{"left": "الرُّكُوع", "right": "سُبْحَانَ رَبِّيَ الْعَظِيم"}, {"left": "السُّجُود", "right": "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, {"left": "الْجُلُوس", "right": "رَبِّ اغْفِرْ لِي"}}}},
				{Type: LessonRevision, Title: "Complete the Tashahhud", Description: "Fill in the blank", ScreenType: ScreenQuiz, Component: "FillBlankComponent", Data: map[string]any{"instruction": "Complete the testimony", "sentence": []map[string]any{{"text": "أَشْهَدُ"}, {"text": "أَنْ"}, {"text": "لَا"}, {"blank": true, "answer": "إِلَٰهَ"}, {"text": "إِلَّا"}, {"text": "اللَّهُ"}}, "bank": []string{"إِلَٰهَ", "النَّبِيُّ", "الصَّالِحِينَ"}, "meaning": "I bear witness that there is no god but Allah"}},
				{Type: LessonManners, Title: "Prayer & Peace", Description: "Reflect on your salah", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "How does praying five times a day help you?", "options": []string{"It keeps me close to Allah", "It calms my heart", "It reminds me of Him all day", "It keeps me away from bad deeds"}}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "Match every posture to its saying", Data: map[string]any{"pairs": []map[string]any{{"left": "الْقِيَام", "right": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ"}, {"left": "الرُّكُوع", "right": "سُبْحَانَ رَبِّيَ الْعَظِيم"}, {"left": "السُّجُود", "right": "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, {"left": "الْجُلُوس", "right": "رَبِّ اغْفِرْ لِي"}, {"left": "التَّسْلِيم", "right": "السَّلَامُ عَلَيْكُم"}}}},
		},
		{
			ID:           30,
			Title:        "You Can Pray!",
			Theme:        "Final Assessment & Celebration",
			Goal:         "Pass the final test and earn your Salah Certificate!",
			Difficulty:   LevelHard,
			XPReward:     350,
			UnlockReward: "badge:salah_graduate",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Final Test: Sujood", Description: "Choose the correct tasbih", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "What do you say in sujood?", "options": []string{"سُبْحَانَ رَبِّيَ الْأَعْلَى", "سُبْحَانَ رَبِّيَ الْعَظِيم", "رَبِّ اغْفِرْ لِي"}, "correct": 0}},
				{Type: LessonRevision, Title: "Final Test: Rak'ahs", Description: "Choose the correct number", ScreenType: ScreenQuiz, Component: "MCQComponent", Data: map[string]any{"question": "How many fard rak'ahs does Maghrib have?", "options": []string{"٣", "٢", "٤"}, "correct": 0}},
				{Type: LessonRevision, Title: "Final Test: Build", Description: "Arrange the opening Takbir", ScreenType: ScreenAction, Component: "AyahBuilderComponent", Data: map[string]any{"instruction": "Build the words that begin the prayer", "parts": []string{"اللَّهُ", "أَكْبَر"}, "meaning": "Allah is the Greatest"}},
				{Type: LessonRevision, Title: "Final Lightning Test", Description: "Everything you learned — fast!", ScreenType: ScreenQuiz, Component: "LightningRoundComponent", Data: map[string]any{"seconds": 8, "questions": []map[string]any{{"question": "What begins the prayer?", "options": []string{"اللَّهُ أَكْبَر", "السَّلَامُ عَلَيْكُم", "آمِين"}, "correct": 0}, {"question": "Tasbih of ruku'?", "options": []string{"سُبْحَانَ رَبِّيَ الْعَظِيم", "سُبْحَانَ رَبِّيَ الْأَعْلَى", "رَبِّ اغْفِرْ لِي"}, "correct": 0}, {"question": "What ends the prayer?", "options": []string{"السَّلَامُ عَلَيْكُم", "اللَّهُ أَكْبَر", "آمِين"}, "correct": 0}, {"question": "How many daily fard prayers?", "options": []string{"٥", "٣", "٧"}, "correct": 0}}}},
				{Type: LessonRevision, Title: "Certificate Ceremony", Description: "Congratulations, you can pray!", ScreenType: ScreenAction, Component: "CertificateComponent", Data: map[string]any{"title": "Salah Graduate", "message": "MashaAllah! You now know how to make wudu, give the Takbir, recite Al-Fatihah, bow in ruku', prostrate in sujood, sit for the Tashahhud, and end with the Salam — and you know the five daily prayers. You are ready to pray!", "next_phase": "Phase 4: Understanding the Qur'an"}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Grand Treasure! Match every posture to its saying", Data: map[string]any{"pairs": []map[string]any{{"left": "التَّكْبِير", "right": "اللَّهُ أَكْبَر"}, {"left": "الْقِيَام", "right": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ"}, {"left": "الرُّكُوع", "right": "سُبْحَانَ رَبِّيَ الْعَظِيم"}, {"left": "السُّجُود", "right": "سُبْحَانَ رَبِّيَ الْأَعْلَى"}, {"left": "الْجُلُوس", "right": "رَبِّ اغْفِرْ لِي"}, {"left": "التَّسْلِيم", "right": "السَّلَامُ عَلَيْكُم"}}}},
		},
	}
}
