// Package reflection holds the Reflection Companion domain: a learner's short
// daily reflection, the warm response, and a curated (referenced) verse. Scripture
// is always retrieved from the curated list — never generated by AI.
package reflection

import (
	"context"
	"time"
)

// Verse is a short, well-known, authentic ayah/hadith with its reference. Used
// "retrieved, not invented" — the AI layer never produces scripture.
type Verse struct {
	Arabic      string   `bson:"arabic" json:"arabic"`
	Translation string   `bson:"translation" json:"translation"`
	Reference   string   `bson:"reference" json:"reference"`
	Source      string   `bson:"source" json:"source"` // "Quran" | "Hadith"
	Moods       []string `bson:"-" json:"-"`           // matching keywords (not persisted/exposed)
}

// Reflection is one journal entry: what the learner wrote and the companion's
// (deterministic or AI) encouragement plus a curated verse.
type Reflection struct {
	ID        string    `bson:"_id" json:"id"`
	UserID    string    `bson:"user_id" json:"user_id"`
	Text      string    `bson:"text" json:"text"`
	Mood      string    `bson:"mood,omitempty" json:"mood,omitempty"`
	Message   string    `bson:"message" json:"message"`
	Verse     *Verse    `bson:"verse,omitempty" json:"verse,omitempty"`
	CreatedAt time.Time `bson:"created_at" json:"created_at"`
}

// Repository persists the reflection journal.
type Repository interface {
	Save(ctx context.Context, r *Reflection) error
	List(ctx context.Context, userID string, limit int) ([]Reflection, error)
}
