package model

// SeedTasks returns the 10 master task templates.
// Task ID "1" (Pray Fajr) is marked as fixed and always included.
func SeedTasks() []DailyTask {
	return []DailyTask{
		{
			ID:             "1",
			Title:          "Pray Fajr",
			Category:       CategorySalah,
			Description:    "Start your day with Fajr prayer",
			ScreenType:     ScreenChecklist,
			Component:      "PrayerChecklistComponent",
			Data:           map[string]any{"steps": []string{"Make Wudu", "Pray 2 Rakat Sunnah", "Pray 2 Rakat Fard"}},
			CompletionType: CompletionButton,
			RewardXP:       20,
			Difficulty:     DifficultyEasy,
			IsFixed:        true,
		},
		{
			ID:             "2",
			Title:          "Read 3 Ayahs",
			Category:       CategoryQuran,
			Description:    "Read and understand Quran",
			ScreenType:     ScreenQuranReader,
			Component:      "QuranReaderComponent",
			Data:           map[string]any{"surah": "Ar-Rahman", "ayahs": []int{1, 2, 3}},
			CompletionType: CompletionButton,
			RewardXP:       15,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "3",
			Title:          "Say Astaghfirullah 33 Times",
			Category:       CategoryDhikr,
			Description:    "Seek forgiveness",
			ScreenType:     ScreenCounter,
			Component:      "CounterComponent",
			Data:           map[string]any{"target": 33, "text": "Astaghfirullah"},
			CompletionType: CompletionCounter,
			RewardXP:       10,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "4",
			Title:          "Learn a Hadith",
			Category:       CategoryLearning,
			Description:    "Read and reflect on Hadith",
			ScreenType:     ScreenHadithCard,
			Component:      "HadithComponent",
			Data:           map[string]any{"hadith": "Actions are judged by intentions", "reference": "Bukhari & Muslim"},
			CompletionType: CompletionButton,
			RewardXP:       15,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "5",
			Title:          "Quick Quiz",
			Category:       CategoryLearning,
			Description:    "Test your knowledge",
			ScreenType:     ScreenQuiz,
			Component:      "QuizComponent",
			Data:           map[string]any{"question": "First pillar of Islam?", "options": []string{"Salah", "Zakat", "Shahada"}, "correct": 2},
			CompletionType: CompletionQuiz,
			RewardXP:       15,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "6",
			Title:          "Listen to Quran",
			Category:       CategoryQuran,
			Description:    "Listen for 5 minutes",
			ScreenType:     ScreenAudioPlayer,
			Component:      "AudioPlayerComponent",
			Data:           map[string]any{"surah": "Al-Mulk", "duration": 300},
			CompletionType: CompletionAuto,
			RewardXP:       15,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "7",
			Title:          "Reflect on Your Day",
			Category:       CategoryReflection,
			Description:    "Think about your actions",
			ScreenType:     ScreenReflection,
			Component:      "ReflectionComponent",
			Data:           map[string]any{"question": "Did you help someone today?", "options": []string{"Yes", "No", "Will try"}},
			CompletionType: CompletionButton,
			RewardXP:       10,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "8",
			Title:          "Follow a Sunnah",
			Category:       CategoryCharacter,
			Description:    "Practice a Sunnah",
			ScreenType:     ScreenTips,
			Component:      "TipsComponent",
			Data:           map[string]any{"tips": []string{"Smile", "Say Bismillah", "Use right hand"}},
			CompletionType: CompletionButton,
			RewardXP:       20,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "9",
			Title:          "Say Alhamdulillah 20 Times",
			Category:       CategoryDhikr,
			Description:    "Show gratitude",
			ScreenType:     ScreenCounter,
			Component:      "CounterComponent",
			Data:           map[string]any{"target": 20, "text": "Alhamdulillah"},
			CompletionType: CompletionCounter,
			RewardXP:       10,
			Difficulty:     DifficultyEasy,
		},
		{
			ID:             "10",
			Title:          "Help Someone",
			Category:       CategorySocial,
			Description:    "Do one act of kindness",
			ScreenType:     ScreenAction,
			Component:      "ActionComponent",
			Data:           map[string]any{"instruction": "Help your parents or a friend today"},
			CompletionType: CompletionButton,
			RewardXP:       20,
			Difficulty:     DifficultyEasy,
		},
	}
}
