package model

// SeedLevels returns the complete 20-level learning journey.
func SeedLevels() []Level {
	return []Level{
		// ───────── LEVELS 1-5: Very Beginner ─────────
		{
			ID:           1,
			Title:        "The First Letter",
			Theme:        "Arabic Alphabet Discovery",
			Goal:         "Learn the first 5 Arabic letters (Alif to Jeem)",
			Difficulty:   LevelEasy,
			XPReward:     50,
			UnlockReward: "badge:first_step",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Meet Alif", Description: "Learn the shape and sound of Alif (ا)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "ا", "name": "Alif", "transliteration": "a", "audio_hint": "Like 'a' in 'apple'"}},
				{Type: LessonQaida, Title: "Baa & Taa", Description: "Learn Baa (ب) and Taa (ت)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ب", "name": "Baa", "transliteration": "b"}, {"letter": "ت", "name": "Taa", "transliteration": "t"}}}},
				{Type: LessonQaida, Title: "Thaa & Jeem", Description: "Learn Thaa (ث) and Jeem (ج)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ث", "name": "Thaa", "transliteration": "th"}, {"letter": "ج", "name": "Jeem", "transliteration": "j"}}}},
				{Type: LessonDua, Title: "Before Eating", Description: "Learn the dua before eating: Bismillah", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ", "transliteration": "Bismillah", "meaning": "In the name of Allah", "context": "Say this before you start eating"}},
				{Type: LessonQuiz, Title: "Letter Check", Description: "Quick quiz on the 5 letters you learned", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter is this: ب?", "options": []string{"Alif", "Baa", "Taa", "Jeem"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Tap the matching Arabic letter and its name", Data: map[string]any{"pairs": []map[string]any{{"arabic": "ا", "english": "Alif"}, {"arabic": "ب", "english": "Baa"}, {"arabic": "ت", "english": "Taa"}, {"arabic": "ث", "english": "Thaa"}, {"arabic": "ج", "english": "Jeem"}}}},
		},
		{
			ID:           2,
			Title:        "More Letters!",
			Theme:        "Arabic Alphabet Expansion",
			Goal:         "Learn letters Haa to Zay (ح to ز)",
			Difficulty:   LevelEasy,
			XPReward:     60,
			UnlockReward: "badge:letter_explorer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Haa & Khaa", Description: "Learn Haa (ح) and Khaa (خ)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ح", "name": "Haa", "transliteration": "h"}, {"letter": "خ", "name": "Khaa", "transliteration": "kh"}}}},
				{Type: LessonQaida, Title: "Daal & Dhaal", Description: "Learn Daal (د) and Dhaal (ذ)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "د", "name": "Daal", "transliteration": "d"}, {"letter": "ذ", "name": "Dhaal", "transliteration": "dh"}}}},
				{Type: LessonQaida, Title: "Raa & Zay", Description: "Learn Raa (ر) and Zay (ز)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ر", "name": "Raa", "transliteration": "r"}, {"letter": "ز", "name": "Zay", "transliteration": "z"}}}},
				{Type: LessonHadith, Title: "Intentions Matter", Description: "Learn the hadith about intentions", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Actions are judged by intentions, and every person will get what they intended.", "reference": "Bukhari & Muslim"}},
				{Type: LessonQuiz, Title: "Letter Match", Description: "Identify the new letters", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter makes the 'kh' sound?", "options": []string{"ح", "خ", "د", "ذ"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "Flip cards to match Arabic letters with their names", Data: map[string]any{"pairs": []map[string]any{{"arabic": "ح", "english": "Haa"}, {"arabic": "خ", "english": "Khaa"}, {"arabic": "د", "english": "Daal"}, {"arabic": "ذ", "english": "Dhaal"}, {"arabic": "ر", "english": "Raa"}, {"arabic": "ز", "english": "Zay"}}}},
		},
		{
			ID:           3,
			Title:        "Halfway There!",
			Theme:        "Arabic Alphabet Continues",
			Goal:         "Learn letters Seen to Daad (س to ض)",
			Difficulty:   LevelEasy,
			XPReward:     70,
			UnlockReward: "title:alphabet_adventurer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Seen & Sheen", Description: "Learn Seen (س) and Sheen (ش)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "س", "name": "Seen", "transliteration": "s"}, {"letter": "ش", "name": "Sheen", "transliteration": "sh"}}}},
				{Type: LessonQaida, Title: "Saad & Daad", Description: "Learn Saad (ص) and Daad (ض)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ص", "name": "Saad", "transliteration": "s (heavy)"}, {"letter": "ض", "name": "Daad", "transliteration": "d (heavy)"}}}},
				{Type: LessonDua, Title: "After Eating", Description: "Learn the dua after eating", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي", "transliteration": "Alhamdu lillahil-ladhi at'amani", "meaning": "All praise is due to Allah who fed me", "context": "Say this after finishing your meal"}},
				{Type: LessonManners, Title: "Say Salam!", Description: "Learn the importance of greeting with Salam", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Say 'Assalamu Alaikum' when you meet someone", "It means 'Peace be upon you'", "The reply is 'Wa Alaikum Assalam'", "Spreading salam spreads love and peace"}}},
				{Type: LessonQuiz, Title: "Letter Review", Description: "Quick review of all letters so far", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter is Sheen?", "options": []string{"س", "ش", "ص", "ض"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match the similar-looking letter pairs", Data: map[string]any{"pairs": []map[string]any{{"arabic": "س", "english": "Seen"}, {"arabic": "ش", "english": "Sheen"}, {"arabic": "ص", "english": "Saad"}, {"arabic": "ض", "english": "Daad"}}}},
		},
		{
			ID:           4,
			Title:        "Almost All Letters!",
			Theme:        "Arabic Alphabet Mastery",
			Goal:         "Learn letters Taa to Ghain (ط to غ) and two key duas",
			Difficulty:   LevelEasy,
			XPReward:     80,
			UnlockReward: "badge:dua_learner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Taa & Dhaa", Description: "Learn heavy Taa (ط) and Dhaa (ظ)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ط", "name": "Taa (heavy)", "transliteration": "t (heavy)"}, {"letter": "ظ", "name": "Dhaa (heavy)", "transliteration": "dh (heavy)"}}}},
				{Type: LessonQaida, Title: "Ain & Ghain", Description: "Learn Ain (ع) and Ghain (غ)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ع", "name": "Ain", "transliteration": "'a"}, {"letter": "غ", "name": "Ghain", "transliteration": "gh"}}}},
				{Type: LessonDua, Title: "Before Sleep", Description: "Learn the dua before sleeping", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", "transliteration": "Bismika Allahumma amutu wa ahya", "meaning": "In Your name, O Allah, I die and I live", "context": "Say this before going to sleep"}},
				{Type: LessonDua, Title: "Waking Up", Description: "Learn the dua upon waking up", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا", "transliteration": "Alhamdu lillahil-ladhi ahyana ba'da ma amatana", "meaning": "All praise is to Allah who gave us life after death", "context": "Say this when you wake up"}},
				{Type: LessonQuiz, Title: "Heavy vs Light", Description: "Distinguish heavy and light letter sounds", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which is the heavy version of 'T'?", "options": []string{"ت", "ط", "ث", "د"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen to the letter sound and choose the correct Arabic letter", Data: map[string]any{"items": []map[string]any{{"letter": "ط", "sound": "taa_heavy"}, {"letter": "ظ", "sound": "dhaa_heavy"}, {"letter": "ع", "sound": "ain"}, {"letter": "غ", "sound": "ghain"}}}},
		},
		{
			ID:           5,
			Title:        "Alphabet Complete!",
			Theme:        "Arabic Alphabet Celebration",
			Goal:         "Learn the final letters (ف to ي) and celebrate completing the alphabet!",
			Difficulty:   LevelEasy,
			XPReward:     100,
			UnlockReward: "badge:alphabet_master",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Faa to Kaaf", Description: "Learn Faa (ف), Qaaf (ق), and Kaaf (ك)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ف", "name": "Faa", "transliteration": "f"}, {"letter": "ق", "name": "Qaaf", "transliteration": "q"}, {"letter": "ك", "name": "Kaaf", "transliteration": "k"}}}},
				{Type: LessonQaida, Title: "Laam to Noon", Description: "Learn Laam (ل), Meem (م), and Noon (ن)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ل", "name": "Laam", "transliteration": "l"}, {"letter": "م", "name": "Meem", "transliteration": "m"}, {"letter": "ن", "name": "Noon", "transliteration": "n"}}}},
				{Type: LessonQaida, Title: "Haa to Yaa", Description: "Learn Haa (ه), Waaw (و), and Yaa (ي)", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ه", "name": "Haa", "transliteration": "h"}, {"letter": "و", "name": "Waaw", "transliteration": "w"}, {"letter": "ي", "name": "Yaa", "transliteration": "y"}}}},
				{Type: LessonHadith, Title: "Cleanliness", Description: "Hadith about cleanliness being half of faith", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Cleanliness is half of faith.", "reference": "Sahih Muslim"}},
				{Type: LessonRevision, Title: "Full Alphabet Review", Description: "Review all 28 Arabic letters", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "How many letters are in the Arabic alphabet?", "options": []string{"26", "27", "28", "29"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Treasure Chest! Match all 28 letters in a memory card challenge", Data: map[string]any{"pairs": []map[string]any{{"arabic": "ف", "english": "Faa"}, {"arabic": "ق", "english": "Qaaf"}, {"arabic": "ك", "english": "Kaaf"}, {"arabic": "ل", "english": "Laam"}, {"arabic": "م", "english": "Meem"}, {"arabic": "ن", "english": "Noon"}, {"arabic": "ه", "english": "Haa"}, {"arabic": "و", "english": "Waaw"}, {"arabic": "ي", "english": "Yaa"}}}},
		},

		// ───────── LEVELS 6-10: Harakat & Pronunciation ─────────
		{
			ID:           6,
			Title:        "Zabar Power!",
			Theme:        "Harakat – Fathah",
			Goal:         "Learn Fathah (zabar) and how it changes letter sounds",
			Difficulty:   LevelMedium,
			XPReward:     100,
			UnlockReward: "badge:harakat_beginner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Fathah?", Description: "Learn that Fathah (  َ ) adds an 'a' sound above the letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بَ", "name": "Baa with Fathah", "transliteration": "ba", "audio_hint": "The small line above makes it 'ba'"}},
				{Type: LessonPronunciation, Title: "Practice Fathah", Description: "Read letters with Fathah: بَ تَ ثَ جَ", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "بَ", "sound": "ba"}, {"arabic": "تَ", "sound": "ta"}, {"arabic": "ثَ", "sound": "tha"}, {"arabic": "جَ", "sound": "ja"}}}},
				{Type: LessonPronunciation, Title: "More Fathah", Description: "Continue with: دَ رَ سَ عَ", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "دَ", "sound": "da"}, {"arabic": "رَ", "sound": "ra"}, {"arabic": "سَ", "sound": "sa"}, {"arabic": "عَ", "sound": "'a"}}}},
				{Type: LessonDua, Title: "Entering Home", Description: "Learn dua for entering your home", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ وَلَجْنَا", "transliteration": "Bismillahi walajna", "meaning": "In the name of Allah we enter", "context": "Say this when entering your home"}},
				{Type: LessonQuiz, Title: "Fathah Quiz", Description: "Identify the correct Fathah pronunciation", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "How do you pronounce بَ?", "options": []string{"bi", "ba", "bu", "b"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Choose the correct pronunciation for each letter with Fathah", Data: map[string]any{"questions": []map[string]any{{"question": "نَ = ?", "options": []string{"na", "ni", "nu"}, "correct": 0}, {"question": "كَ = ?", "options": []string{"ki", "ku", "ka"}, "correct": 2}}}},
		},
		{
			ID:           7,
			Title:        "Zer & Pesh",
			Theme:        "Harakat – Kasrah & Dammah",
			Goal:         "Learn Kasrah (zer) and Dammah (pesh) to complete the three harakat",
			Difficulty:   LevelMedium,
			XPReward:     110,
			UnlockReward: "badge:harakat_explorer",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Kasrah?", Description: "Learn that Kasrah (  ِ ) adds an 'i' sound below the letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بِ", "name": "Baa with Kasrah", "transliteration": "bi", "audio_hint": "The small line below makes it 'bi'"}},
				{Type: LessonQaida, Title: "What is Dammah?", Description: "Learn that Dammah (  ُ ) adds a 'u' sound above the letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بُ", "name": "Baa with Dammah", "transliteration": "bu", "audio_hint": "The small waw shape above makes it 'bu'"}},
				{Type: LessonPronunciation, Title: "All Three Harakat", Description: "Practice: بَ بِ بُ / تَ تِ تُ / سَ سِ سُ", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "بَ بِ بُ", "sound": "ba-bi-bu"}, {"arabic": "تَ تِ تُ", "sound": "ta-ti-tu"}, {"arabic": "سَ سِ سُ", "sound": "sa-si-su"}}}},
				{Type: LessonHadith, Title: "Kindness", Description: "Hadith on being kind to others", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Allah is kind and loves kindness in all matters.", "reference": "Bukhari & Muslim"}},
				{Type: LessonQuiz, Title: "Three Harakat", Description: "Identify Fathah, Kasrah, or Dammah", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which harakat makes the 'u' sound?", "options": []string{"Fathah (zabar)", "Kasrah (zer)", "Dammah (pesh)", "Sukoon"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Drag the correct harakat symbol onto each letter to form the given sound", Data: map[string]any{"items": []map[string]any{{"letter": "ن", "target_sound": "ni", "correct_harakat": "kasrah"}, {"letter": "م", "target_sound": "mu", "correct_harakat": "dammah"}, {"letter": "ل", "target_sound": "la", "correct_harakat": "fathah"}}}},
		},
		{
			ID:           8,
			Title:        "Two-Letter Words",
			Theme:        "Building Blocks",
			Goal:         "Combine letters with harakat to read your first 2-letter Arabic words",
			Difficulty:   LevelMedium,
			XPReward:     120,
			UnlockReward: "title:word_builder",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Sukoon?", Description: "Learn that Sukoon (  ْ ) makes a letter silent/stopping", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "بْ", "name": "Baa with Sukoon", "transliteration": "-b", "audio_hint": "No vowel – just the 'b' sound at the end"}},
				{Type: LessonPronunciation, Title: "First Words!", Description: "Read simple 2-letter combinations: أَبْ (ab), أُمْ (um), مِنْ (min)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "أَبْ", "sound": "ab"}, {"arabic": "أُمْ", "sound": "um"}, {"arabic": "مِنْ", "sound": "min"}}}},
				{Type: LessonPronunciation, Title: "More 2-Letter Words", Description: "Read: قُلْ (qul), لَمْ (lam), هَلْ (hal)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "قُلْ", "sound": "qul"}, {"arabic": "لَمْ", "sound": "lam"}, {"arabic": "هَلْ", "sound": "hal"}}}},
				{Type: LessonManners, Title: "Helping Others", Description: "Learn the Islamic value of helping others", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Helping others is a form of sadaqah", "Even a smile is charity in Islam", "Help your family with chores", "Be the first to offer help"}}},
				{Type: LessonQuiz, Title: "Word Reading", Description: "Read the word and pick the correct pronunciation", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "How do you read: قُلْ?", "options": []string{"qal", "qil", "qul", "quul"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match each 2-letter word with its pronunciation", Data: map[string]any{"pairs": []map[string]any{{"arabic": "أَبْ", "english": "ab"}, {"arabic": "أُمْ", "english": "um"}, {"arabic": "مِنْ", "english": "min"}, {"arabic": "قُلْ", "english": "qul"}, {"arabic": "هَلْ", "english": "hal"}}}},
		},
		{
			ID:           9,
			Title:        "Three-Letter Words",
			Theme:        "Growing Confidence",
			Goal:         "Read your first 3-letter Arabic words",
			Difficulty:   LevelMedium,
			XPReward:     130,
			UnlockReward: "badge:reader_rising",
			Lessons: []Lesson{
				{Type: LessonPronunciation, Title: "3-Letter Words", Description: "Read: كَتَبَ (kataba), جَلَسَ (jalasa), فَتَحَ (fataha)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "كَتَبَ", "sound": "ka-ta-ba"}, {"arabic": "جَلَسَ", "sound": "ja-la-sa"}, {"arabic": "فَتَحَ", "sound": "fa-ta-ha"}}}},
				{Type: LessonPronunciation, Title: "More Words", Description: "Read: نَصَرَ (nasara), ذَهَبَ (dhahaba)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "نَصَرَ", "sound": "na-sa-ra"}, {"arabic": "ذَهَبَ", "sound": "dha-ha-ba"}}}},
				{Type: LessonHadith, Title: "Truthfulness", Description: "Hadith about telling the truth", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Truthfulness leads to righteousness and righteousness leads to Paradise.", "reference": "Bukhari & Muslim"}},
				{Type: LessonDua, Title: "Leaving Home", Description: "Learn dua for leaving your home", ScreenType: ScreenHadithCard, Component: "DuaCardComponent", Data: map[string]any{"arabic": "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ", "transliteration": "Bismillahi tawakkaltu 'alallah", "meaning": "In the name of Allah, I place my trust in Allah", "context": "Say this when leaving your home"}},
				{Type: LessonQuiz, Title: "3-Letter Check", Description: "Read the word and choose correct answer", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "How do you read: كَتَبَ?", "options": []string{"kutiba", "kataba", "kitaab", "kutub"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Choose the correct pronunciation for each 3-letter word", Data: map[string]any{"questions": []map[string]any{{"question": "جَلَسَ = ?", "options": []string{"jalasa", "julisa", "jalees"}, "correct": 0}, {"question": "نَصَرَ = ?", "options": []string{"nusira", "nasara", "nasr"}, "correct": 1}}}},
		},
		{
			ID:           10,
			Title:        "Tanween Time!",
			Theme:        "Double Harakat",
			Goal:         "Learn Tanween (double marks) and apply them to words",
			Difficulty:   LevelMedium,
			XPReward:     150,
			UnlockReward: "badge:tanween_master",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Tanween Fathah", Description: "Learn that ً makes an '-an' ending sound", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "كِتَابًا", "name": "Tanween Fathah", "transliteration": "kitaaban", "audio_hint": "Double fathah = '-an' sound at the end"}},
				{Type: LessonQaida, Title: "Tanween Kasrah", Description: "Learn that ٍ makes an '-in' ending sound", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "كِتَابٍ", "name": "Tanween Kasrah", "transliteration": "kitaabin", "audio_hint": "Double kasrah = '-in' sound at the end"}},
				{Type: LessonQaida, Title: "Tanween Dammah", Description: "Learn that ٌ makes an '-un' ending sound", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "كِتَابٌ", "name": "Tanween Dammah", "transliteration": "kitaabun", "audio_hint": "Double dammah = '-un' sound at the end"}},
				{Type: LessonManners, Title: "Respect Elders", Description: "Learn Islamic etiquette of respecting elders", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Stand up for elders when they enter", "Speak softly and respectfully", "Listen without interrupting", "The Prophet ﷺ said: 'He is not one of us who does not respect our elders'"}}},
				{Type: LessonQuiz, Title: "Tanween Quiz", Description: "Identify which tanween is used", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What sound does ً (double fathah) add?", "options": []string{"-an", "-in", "-un", "-aa"}, "correct": 0}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Treasure Chest! Match tanween words with their pronunciation", Data: map[string]any{"pairs": []map[string]any{{"arabic": "عِلْمًا", "english": "'ilman"}, {"arabic": "عِلْمٍ", "english": "'ilmin"}, {"arabic": "عِلْمٌ", "english": "'ilmun"}, {"arabic": "نُورًا", "english": "nooran"}, {"arabic": "نُورٍ", "english": "noorin"}, {"arabic": "نُورٌ", "english": "noorun"}}}},
		},

		// ───────── LEVELS 11-15: Joining Letters & Simple Quran ─────────
		{
			ID:           11,
			Title:        "Letters Connect",
			Theme:        "Joining Arabic Letters",
			Goal:         "Understand how Arabic letters change shape when joined",
			Difficulty:   LevelMedium,
			XPReward:     150,
			UnlockReward: "badge:connector",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Letter Forms", Description: "Learn that letters have isolated, initial, medial, and final forms", ScreenType: ScreenAction, Component: "LetterFormsComponent", Data: map[string]any{"letter": "ب", "forms": map[string]any{"isolated": "ب", "initial": "بـ", "medial": "ـبـ", "final": "ـب"}}},
				{Type: LessonQaida, Title: "Non-Connecting Letters", Description: "Learn the 6 letters that don't connect to the left: ا د ذ ر ز و", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letters": []map[string]any{{"letter": "ا", "name": "Alif"}, {"letter": "د", "name": "Daal"}, {"letter": "ذ", "name": "Dhaal"}, {"letter": "ر", "name": "Raa"}, {"letter": "ز", "name": "Zay"}, {"letter": "و", "name": "Waaw"}}, "note": "These 6 never connect to the letter after them"}},
				{Type: LessonPronunciation, Title: "Read Joined Words", Description: "Read connected words: بسم (bism), كتب (kutub)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "بِسْمِ", "sound": "bis-mi"}, {"arabic": "كُتُبْ", "sound": "ku-tub"}}}},
				{Type: LessonHadith, Title: "Smiling is Charity", Description: "Beautiful hadith about smiling", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Your smiling in the face of your brother is charity.", "reference": "Tirmidhi"}},
				{Type: LessonQuiz, Title: "Connection Quiz", Description: "Which letters don't connect?", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter does NOT connect to the next letter?", "options": []string{"ب", "ت", "ر", "ن"}, "correct": 2}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Drag letters together to form connected Arabic words", Data: map[string]any{"words": []map[string]any{{"letters": []string{"ب", "س", "م"}, "result": "بسم"}, {"letters": []string{"ك", "ت", "ب"}, "result": "كتب"}}}},
		},
		{
			ID:           12,
			Title:        "Simple Quran Words",
			Theme:        "First Quran Reading",
			Goal:         "Read simple words that appear in the Quran",
			Difficulty:   LevelMedium,
			XPReward:     160,
			UnlockReward: "title:quran_beginner",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Bismillah", Description: "Read the most common phrase: بِسْمِ اللَّهِ", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Common Phrase", "text": "بِسْمِ اللَّهِ", "transliteration": "Bismillah", "meaning": "In the name of Allah"}},
				{Type: LessonPronunciation, Title: "Allah & Rabb", Description: "Read: اللَّه (Allah), رَبّ (Rabb - Lord)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "اللَّه", "sound": "Al-laah"}, {"arabic": "رَبّ", "sound": "Rabb"}}}},
				{Type: LessonPronunciation, Title: "More Quran Words", Description: "Read: نُور (Noor - Light), عِلْم ('Ilm - Knowledge), حَقّ (Haqq - Truth)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "نُور", "sound": "noor"}, {"arabic": "عِلْم", "sound": "'ilm"}, {"arabic": "حَقّ", "sound": "haqq"}}}},
				{Type: LessonManners, Title: "Gratitude (Shukr)", Description: "Learn the sunnah of being grateful", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Say Alhamdulillah for every blessing", "Thank people who help you", "Be grateful for small things", "Gratitude increases blessings (Quran 14:7)"}}},
				{Type: LessonQuiz, Title: "Quran Word Quiz", Description: "Match the word to its meaning", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What does نُور mean?", "options": []string{"Knowledge", "Light", "Truth", "Lord"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameTapMatch, Description: "Match Quran words to their meanings", Data: map[string]any{"pairs": []map[string]any{{"arabic": "اللَّه", "english": "Allah"}, {"arabic": "رَبّ", "english": "Lord"}, {"arabic": "نُور", "english": "Light"}, {"arabic": "عِلْم", "english": "Knowledge"}, {"arabic": "حَقّ", "english": "Truth"}}}},
		},
		{
			ID:           13,
			Title:        "Madd Basics",
			Theme:        "Elongation Rules",
			Goal:         "Learn the three Madd letters and how they elongate sounds",
			Difficulty:   LevelMedium,
			XPReward:     160,
			UnlockReward: "badge:tajweed_starter",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "What is Madd?", Description: "Madd means stretching. Three letters cause elongation: ا و ي", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مَا", "name": "Madd with Alif", "transliteration": "maa", "audio_hint": "Stretch the 'a' sound for 2 counts"}},
				{Type: LessonPronunciation, Title: "Madd with Alif", Description: "Practice: قَالَ (qaala), بَابْ (baab), نَارْ (naar)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "قَالَ", "sound": "qaa-la"}, {"arabic": "بَابْ", "sound": "baab"}, {"arabic": "نَارْ", "sound": "naar"}}}},
				{Type: LessonPronunciation, Title: "Madd with Waaw & Yaa", Description: "Practice: نُورْ (noor), يَقُولُ (yaqoolu), دِينْ (deen)", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "نُورْ", "sound": "noor"}, {"arabic": "يَقُولُ", "sound": "ya-qoo-lu"}, {"arabic": "دِينْ", "sound": "deen"}}}},
				{Type: LessonHadith, Title: "Respect Parents", Description: "Hadith about the importance of respecting parents", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The pleasure of Allah lies in the pleasure of the parents, and the displeasure of Allah lies in the displeasure of the parents.", "reference": "Tirmidhi"}},
				{Type: LessonQuiz, Title: "Madd Quiz", Description: "Identify the Madd letter", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter causes Madd in قَالَ?", "options": []string{"ق", "ا", "ل", "None"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen and identify which word has a Madd (elongation)", Data: map[string]any{"items": []map[string]any{{"word": "قَالَ", "has_madd": true}, {"word": "قُلْ", "has_madd": false}, {"word": "نُورْ", "has_madd": true}, {"word": "مِنْ", "has_madd": false}}}},
		},
		{
			ID:           14,
			Title:        "Sunnah Lifestyle",
			Theme:        "Daily Sunnah Habits",
			Goal:         "Learn daily sunnah practices and review reading skills",
			Difficulty:   LevelMedium,
			XPReward:     140,
			UnlockReward: "badge:sunnah_follower",
			Lessons: []Lesson{
				{Type: LessonManners, Title: "Morning Sunnahs", Description: "Start your day the Prophet's ﷺ way", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Wake up and say the morning dua", "Use miswak to clean your teeth", "Pray Fajr on time", "Read morning adhkar", "Eat suhoor if fasting"}}},
				{Type: LessonManners, Title: "Evening Sunnahs", Description: "End your day with blessings", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Read evening adhkar before sunset", "Pray Isha and Witr", "Read Ayatul Kursi before bed", "Sleep on your right side", "Recite the 3 Quls"}}},
				{Type: LessonManners, Title: "Patience (Sabr)", Description: "Learn about patience in Islam", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "When do you find it hardest to be patient?", "options": []string{"When someone is rude to me", "When things don't go my way", "When I have to wait for something", "When I'm tired or hungry"}}},
				{Type: LessonRevision, Title: "Reading Review", Description: "Review words from previous levels", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "How do you read: بِسْمِ اللَّهِ?", "options": []string{"Bismillah", "Alhamdulillah", "SubhanAllah", "Allahu Akbar"}, "correct": 0}},
				{Type: LessonDua, Title: "Dua Compilation", Description: "Quick revision of all duas learned so far", ScreenType: ScreenChecklist, Component: "PrayerChecklistComponent", Data: map[string]any{"steps": []string{"Before eating: Bismillah ✓", "After eating: Alhamdulillah ✓", "Before sleep dua ✓", "Waking up dua ✓", "Entering home dua ✓", "Leaving home dua ✓"}}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Test your knowledge of daily sunnahs and duas", Data: map[string]any{"questions": []map[string]any{{"question": "What do you say before eating?", "options": []string{"Bismillah", "Alhamdulillah", "SubhanAllah"}, "correct": 0}, {"question": "On which side should you sleep?", "options": []string{"Left", "Right", "Back"}, "correct": 1}}}},
		},
		{
			ID:           15,
			Title:        "Checkpoint Alpha",
			Theme:        "Mid-Journey Revision",
			Goal:         "Complete a comprehensive review of everything learned so far",
			Difficulty:   LevelMedium,
			XPReward:     200,
			UnlockReward: "badge:checkpoint_hero",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Alphabet Mastery", Description: "Test all 28 letters recognition", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letter is خ?", "options": []string{"Haa", "Khaa", "Jeem", "Ghain"}, "correct": 1}},
				{Type: LessonRevision, Title: "Harakat Mastery", Description: "Test Fathah, Kasrah, Dammah, Sukoon, Tanween", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What does Tanween ً add to a word?", "options": []string{"-an sound", "-in sound", "-un sound", "silence"}, "correct": 0}},
				{Type: LessonRevision, Title: "Word Reading", Description: "Read mixed 2 and 3 letter words", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "كَتَبَ", "sound": "ka-ta-ba"}, {"arabic": "نُورْ", "sound": "noor"}, {"arabic": "قَالَ", "sound": "qaa-la"}, {"arabic": "هَلْ", "sound": "hal"}}}},
				{Type: LessonRevision, Title: "Dua & Hadith Recall", Description: "How many duas and hadith can you remember?", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "Which hadith resonated with you the most?", "options": []string{"Actions are judged by intentions", "Cleanliness is half of faith", "Smiling is charity", "Truthfulness leads to paradise"}}},
				{Type: LessonRevision, Title: "Madd & Joining", Description: "Review elongation and letter connections", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Which letters DON'T connect to the next letter?", "options": []string{"ب ت ث", "ا د ذ ر ز و", "ف ق ك", "ل م ن"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Treasure Chest! Grand review memory card challenge", Data: map[string]any{"pairs": []map[string]any{{"arabic": "بِسْمِ اللَّه", "english": "In the name of Allah"}, {"arabic": "الحَمْدُ لِلَّه", "english": "All praise to Allah"}, {"arabic": "نُور", "english": "Light"}, {"arabic": "عِلْم", "english": "Knowledge"}, {"arabic": "حَقّ", "english": "Truth"}, {"arabic": "رَبّ", "english": "Lord"}}}},
		},

		// ───────── LEVELS 16-20: Quran Reading & Graduation ─────────
		{
			ID:           16,
			Title:        "Al-Fatihah Prep",
			Theme:        "Reading Surah Al-Fatihah",
			Goal:         "Start reading the first verse of Al-Fatihah",
			Difficulty:   LevelHard,
			XPReward:     200,
			UnlockReward: "title:quran_reader",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Bismillah Complete", Description: "Read بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ with proper pronunciation", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Fatihah", "text": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", "transliteration": "Bismillahir Rahmanir Raheem", "meaning": "In the name of Allah, the Most Gracious, the Most Merciful"}},
				{Type: LessonQaida, Title: "Shaddah Introduction", Description: "Learn that Shaddah ( ّ ) doubles a letter's sound", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "الرَّحْمَٰنِ", "name": "Shaddah on Raa", "transliteration": "ar-Rahman", "audio_hint": "Shaddah means press the letter harder and longer"}},
				{Type: LessonPronunciation, Title: "Al-Fatihah Line 2", Description: "Read: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Fatihah", "text": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", "transliteration": "Alhamdu lillahi Rabbil 'aalameen", "meaning": "All praise is due to Allah, Lord of all the worlds"}},
				{Type: LessonHadith, Title: "Best of You", Description: "Hadith about learning and teaching Quran", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "The best of you are those who learn the Quran and teach it.", "reference": "Bukhari"}},
				{Type: LessonQuiz, Title: "Al-Fatihah Check", Description: "Verify your understanding", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What does الرَّحْمَٰنِ mean?", "options": []string{"The Lord", "The Most Gracious", "The All-Knowing", "The Creator"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameListenChoose, Description: "Listen to each word of Al-Fatihah and choose the correct Arabic text", Data: map[string]any{"items": []map[string]any{{"word": "بِسْمِ", "options": []string{"بِسْمِ", "نِسْمِ", "بِشْمِ"}}, {"word": "اللَّهِ", "options": []string{"الْلَهِ", "اللَّهِ", "اللَحِ"}}}}},
		},
		{
			ID:           17,
			Title:        "Tajweed Essentials",
			Theme:        "Basic Tajweed Rules",
			Goal:         "Learn Noon Sakinah, Tanween rules, and Qalqalah basics",
			Difficulty:   LevelHard,
			XPReward:     220,
			UnlockReward: "badge:tajweed_student",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Noon Sakinah Rules", Description: "When Noon has sukoon, special rules apply based on the next letter", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مِنْ بَعْدِ", "name": "Ikhfaa Example", "transliteration": "mim-ba'di", "audio_hint": "The noon is hidden (ikhfaa) before Baa"}},
				{Type: LessonQaida, Title: "Idghaam Basics", Description: "When Noon Sakin meets و ي ن م ل ر the noon merges", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "مِنْ رَبِّ", "name": "Idghaam Example", "transliteration": "mir-Rabbi", "audio_hint": "The noon merges into the Raa"}},
				{Type: LessonQaida, Title: "Qalqalah Letters", Description: "Learn the 5 bouncing letters: ق ط ب ج د", ScreenType: ScreenAction, Component: "LetterIntroComponent", Data: map[string]any{"letter": "قُطْبُ جَدٍّ", "name": "Qalqalah", "transliteration": "qutbu jadd", "audio_hint": "These letters bounce when they have sukoon"}},
				{Type: LessonPronunciation, Title: "Tajweed Practice", Description: "Apply rules to Quran phrases", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "مِنْ بَعْدِ", "sound": "mim-ba'di (ikhfaa)"}, {"arabic": "مِنْ رَبِّكَ", "sound": "mir-Rabbika (idghaam)"}, {"arabic": "أَحَدْ", "sound": "ahad (qalqalah)"}}}},
				{Type: LessonQuiz, Title: "Tajweed Quiz", Description: "Identify the tajweed rule", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What happens to Noon Sakin before ر?", "options": []string{"It stays clear (Izhar)", "It merges (Idghaam)", "It is hidden (Ikhfaa)", "It flips (Iqlab)"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameDragDrop, Description: "Drag Quran phrases to their correct tajweed rule category", Data: map[string]any{"categories": []string{"Idghaam", "Ikhfaa", "Izhar", "Qalqalah"}, "items": []map[string]any{{"phrase": "مِنْ رَبِّ", "category": "Idghaam"}, {"phrase": "مِنْ بَعْدِ", "category": "Ikhfaa"}, {"phrase": "أَحَدْ", "category": "Qalqalah"}}}},
		},
		{
			ID:           18,
			Title:        "Short Surahs",
			Theme:        "Reading Complete Surahs",
			Goal:         "Read Surah Al-Ikhlas and Al-Falaq with understanding",
			Difficulty:   LevelHard,
			XPReward:     230,
			UnlockReward: "title:surah_scholar",
			Lessons: []Lesson{
				{Type: LessonQaida, Title: "Surah Al-Ikhlas", Description: "Read the complete Surah: قُلْ هُوَ اللَّهُ أَحَدٌ", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Ikhlas (112)", "text": "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", "transliteration": "Qul huwal laahu ahad. Allahus samad. Lam yalid wa lam yoolad. Wa lam yakul lahu kufuwan ahad.", "meaning": "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent."}},
				{Type: LessonPronunciation, Title: "Surah Al-Falaq", Description: "Read: قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Falaq (113)", "text": "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ", "transliteration": "Qul a'udhu bi Rabbil falaq. Min sharri ma khalaq.", "meaning": "Say: I seek refuge in the Lord of daybreak. From the evil of that which He created."}},
				{Type: LessonRevision, Title: "Tajweed in Surahs", Description: "Identify tajweed rules in Al-Ikhlas", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "In 'لَمْ يَلِدْ', what rule applies to the دْ?", "options": []string{"Madd", "Idghaam", "Qalqalah", "Ikhfaa"}, "correct": 2}},
				{Type: LessonManners, Title: "Character Building", Description: "Core Islamic character traits", ScreenType: ScreenReflection, Component: "ReflectionComponent", Data: map[string]any{"question": "Which character trait would you like to develop more?", "options": []string{"Honesty (Sidq)", "Patience (Sabr)", "Gratitude (Shukr)", "Generosity (Karam)", "Humility (Tawadu')"}}},
				{Type: LessonQuiz, Title: "Surah Understanding", Description: "Test your understanding", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What is the main message of Surah Al-Ikhlas?", "options": []string{"Story of prophets", "Oneness of Allah", "Day of Judgment", "Paradise"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameMCQ, Description: "Answer questions about the surahs you just read", Data: map[string]any{"questions": []map[string]any{{"question": "How many ayahs in Al-Ikhlas?", "options": []string{"3", "4", "5"}, "correct": 1}, {"question": "الصَّمَدُ means?", "options": []string{"The One", "The Eternal Refuge", "The Creator"}, "correct": 1}}}},
		},
		{
			ID:           19,
			Title:        "Confidence Builder",
			Theme:        "Fluent Reading Practice",
			Goal:         "Practice reading multiple Quran phrases with speed and accuracy",
			Difficulty:   LevelHard,
			XPReward:     250,
			UnlockReward: "badge:confident_reader",
			Lessons: []Lesson{
				{Type: LessonPronunciation, Title: "Speed Reading 1", Description: "Read these phrases smoothly: الْحَمْدُ لِلَّهِ / سُبْحَانَ اللَّهِ / لَا إِلَٰهَ إِلَّا اللَّه", ScreenType: ScreenAction, Component: "PronunciationComponent", Data: map[string]any{"items": []map[string]any{{"arabic": "الْحَمْدُ لِلَّهِ", "sound": "Al-hamdu lillah"}, {"arabic": "سُبْحَانَ اللَّهِ", "sound": "Sub-haa-nal-laah"}, {"arabic": "لَا إِلَٰهَ إِلَّا اللَّه", "sound": "Laa ilaaha illal-laah"}}}},
				{Type: LessonQaida, Title: "Ayatul Kursi Preview", Description: "Read the beginning of the greatest ayah", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Al-Baqarah 2:255", "text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", "transliteration": "Allahu laa ilaaha illa Huwal Hayyul Qayyoom", "meaning": "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence"}},
				{Type: LessonRevision, Title: "Makharij Review", Description: "Quick review of letter pronunciation origins", ScreenType: ScreenTips, Component: "TipsComponent", Data: map[string]any{"tips": []string{"Throat letters: ع غ ح خ ه ء", "Tongue letters: most Arabic letters", "Lip letters: ب م و ف", "Nasal letters: نّ مّ (with shaddah)", "Practice each group separately for clarity"}}},
				{Type: LessonHadith, Title: "Reward of Reading", Description: "Motivation to continue reading Quran", ScreenType: ScreenHadithCard, Component: "HadithComponent", Data: map[string]any{"hadith": "Whoever reads a letter from the Book of Allah will have a reward, and that reward will be multiplied by ten.", "reference": "Tirmidhi"}},
				{Type: LessonQuiz, Title: "Reading Challenge", Description: "Final reading comprehension check", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "What does الْحَيُّ الْقَيُّومُ mean?", "options": []string{"The Most Gracious", "The Ever-Living, The Sustainer", "The All-Knowing", "The Most Merciful"}, "correct": 1}},
			},
			MiniGame: MiniGame{Type: GameRepeatVoice, Description: "Listen and repeat Quran phrases with correct tajweed", Data: map[string]any{"phrases": []map[string]any{{"arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", "transliteration": "Bismillahir Rahmanir Raheem"}, {"arabic": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", "transliteration": "Alhamdu lillahi Rabbil 'aalameen"}}}},
		},
		{
			ID:           20,
			Title:        "Beginner Graduation!",
			Theme:        "Final Assessment & Celebration",
			Goal:         "Complete the beginner graduation test and earn your Qaida Certificate!",
			Difficulty:   LevelHard,
			XPReward:     300,
			UnlockReward: "badge:qaida_graduate",
			Lessons: []Lesson{
				{Type: LessonRevision, Title: "Final Test: Letters", Description: "Identify all 28 Arabic letters correctly", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Final Test Q1: Identify this letter — غ", "options": []string{"Ain", "Ghain", "Faa", "Qaaf"}, "correct": 1}},
				{Type: LessonRevision, Title: "Final Test: Harakat", Description: "Apply all harakat and tanween correctly", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Final Test Q2: How do you read مُسْلِمٌ?", "options": []string{"Musliman", "Muslimun", "Muslimin", "Muslimaan"}, "correct": 1}},
				{Type: LessonRevision, Title: "Final Test: Reading", Description: "Read a complete Quran ayah", ScreenType: ScreenQuranReader, Component: "QuranReaderComponent", Data: map[string]any{"surah": "Graduation Ayah", "text": "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", "transliteration": "Innaa a'taynakal kawthar", "meaning": "Indeed, We have granted you Al-Kawthar (abundance)"}},
				{Type: LessonRevision, Title: "Final Test: Tajweed", Description: "Identify tajweed rules in practice", ScreenType: ScreenQuiz, Component: "QuizComponent", Data: map[string]any{"question": "Final Test Q3: What tajweed rule is in إِنَّا?", "options": []string{"Ghunnah (nasal sound)", "Qalqalah", "Madd", "Idghaam"}, "correct": 0}},
				{Type: LessonRevision, Title: "Certificate Ceremony", Description: "Congratulations! You've completed the Beginner Qaida Journey!", ScreenType: ScreenAction, Component: "CertificateComponent", Data: map[string]any{"title": "Qaida Graduate", "message": "MashaAllah! You can now recognize all Arabic letters, read with harakat, understand basic tajweed, and read simple Quran ayahs. Your journey to fluent Quran reading has begun!", "next_phase": "Phase 3: Intermediate Quran Reading"}},
			},
			MiniGame: MiniGame{Type: GameMemoryCards, Description: "🎁 Grand Treasure Chest! Final graduation celebration challenge", Data: map[string]any{"pairs": []map[string]any{{"arabic": "بِسْمِ اللَّهِ", "english": "In the name of Allah"}, {"arabic": "الْحَمْدُ لِلَّهِ", "english": "All praise to Allah"}, {"arabic": "سُبْحَانَ اللَّهِ", "english": "Glory to Allah"}, {"arabic": "اللَّهُ أَكْبَرُ", "english": "Allah is the Greatest"}, {"arabic": "لَا إِلَٰهَ إِلَّا اللَّه", "english": "No god but Allah"}, {"arabic": "أَسْتَغْفِرُ اللَّه", "english": "I seek Allah's forgiveness"}}}},
		},
	}
}
